### ISSUE TITLE
Arrays as ordered lists or unordered sets

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#12]
In JSON arrays are defined as being ordered lists, the underlying data model of JSON-LD is a directed graph which is inherently unordered. So there is a conflict. Either we bias the approach towards JSON and convert arrays to ordered lists or we design JSON-LD so that it treats arrays as unordered sets.

Treating arrays as ordered lists by default will probably result in "messy" RDF and some argue the developers most of the time don't care about the order anyway.

There are basically three possible solutions we came up with on the [telecon](http://json-ld.org/minutes/2011-08-23/):
- leave everything as it is (arrays are considered as unordered sets)
- consider arrays as ordered lists, add @set keyword
- introduce a mechanisms to define in the context how to treat arrays by default

**Comment by gkellogg** [comment]
Seriously don't think this will ever be re-visited.

**Comment by lanthaler** [comment]
Agreed. This ship has sailed
