### ISSUE TITLE
Consider objectify/link API method

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#140]
Objectify is a mechanism proposed to turn JSON-LD into JavaScript (or other host language) objects with subject references replaced with links to actual objects. Originally proposed by @jmandel in issue #109 as a means of flattening a graph, applying a context, and replacing subject references with in-memory object links.

Alternate names have been suggested, as no-one's thrilled with _objectify_.
- _graphify_ would make it clear that we're turning a tree into a graph
- _link_ goes along with the notion of object linking implied in the name JSON-LD, and uses the term linking to apply to in-memory links as well as external links.
- _connect_ has the connotation of connecting references together.

Given that we've adopted a _flatten_ API method already, partly to help support framing, and context application is implied in expansion, compaction and flattening already, the _objectify_ API method really only need concern itself with replacing subject references with in-memory references.

Conversation took place on the [June 26, 2012 telecon](http://json-ld.org/minutes/2012-06-26/#topic-3).
## Search

For _objectify_ to serve as a potential replacement for _framing_, we also need to have a means of surfacing nodes within a graph.
- [JSON Select](http://jsonselect.org) is one tool that can be used to generically select JSON, similar to using CSS selectors.
- [BGP](http://www.w3.org/TR/rdf-sparql-query/#BasicGraphPatterns) An implementation of BGP against JavaScript data structures would provide a normative path to full SPARQL query support of JSON-LD graphs, in this case, using framing-like syntax to define JSON structures which would be used for matching against JavaScript objects.
## Concerns

Need to make sure code doesn't cycle when traversing such graphs, but if we flatten first, and keep track of visited nodes, this should ensure we don't loop.

**Comment by gkellogg** [comment]
I propose taking this off of the 1.1 milestone; please 👍 or 👎.

**Comment by dlongley** [comment]
I'd like to see the `@link` feature in framing move forward rather than a new API call.

**Comment by dlongley** [comment]
@gkellogg are we :+1: for removing and :-1: for keeping? I did a :+1: for taking this off the 1.1 milestone.

**Comment by gkellogg** [comment]
@dlongley 👍 to accept the proposal, and take off the 1.1 milestone. If you think this is handled by the `@link` feature, and would like to keep it in 1.1, can you propose text to be added to Framing (shouldn't be hard)? Not sure how to test this, given the need to serialize, which can't really be done with `@link`; ideas?

**Comment by dlongley** [comment]
@gkellogg,

> If you think this is handled by the @link feature...

Yes, it is, I've implemented it.

> ...and would like to keep it in 1.1...

I'm not totally convinced it's ready. The `@link` feature is available in several implementations now but there may be some lingering questions about how it ought to work in some edge cases. So we may want to wait unless there's a groundswell of support to move forward with it (and that doesn't yet seem to be the case).

>  Not sure how to test this, given the need to serialize, which can't really be done with @link; ideas?

I haven't tried to figure anything out that isn't based on very customized testing yet. Off the top of my head, we could have a set of "paths" (that may include cycles) that the test suite will attempt to follow/dereference in the output to check object references and find some expected value. For example:

Test expectation data:

```js
{
  "testPaths": [
    {
      "path": [
        {"object": 1, "term1"},
        {"object": 2, "term2"},
        {"object": 1, "term3"}
      ],
      "expected": "foo"
    }
  ]
}
```

This test output would pass:

```js
{
  "@id": "root",
  "term1": {
    "@id": "nested",
    "term2": {/* cyclic link back to "root" */}
  },
  "term3": "foo"
}
```

Our test harness would build some code to assert that the same objects (in memory) were used where appropriate and that the expected value was found.

**Comment by gkellogg** [comment]
Okay, great. Pending further votes, we'll take it out of 1.1.

BTW, I've implemented it too, but don't have tests. We'd need to define a new kind of test, as you expect, that would look for specific paths in memory using something like you suggest.
