### ISSUE TITLE
Drop empty arrays (sets) and empty lists in expansion

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#220]
Now that we remove free-floating values and nodes during expansion, shouldn't we also drop empty arrays (sets) and empty lists?

For example:

```
{
  "@context": {
    "name": "http://xmlns.com/foaf/0.1/name",
    "homepage": {
      "@id": "http://xmlns.com/foaf/0.1/homepage",
      "@type": "@id"
    }
  },
  "@id": "http://me.markus-lanthaler.com/",
  "name": "Markus Lanthaler",
  "homepage": [ ]
}
```

Shouldn't we drop the homepage property when expanding?

```
[
  {
    "@id": "http://me.markus-lanthaler.com/",
    "http://xmlns.com/foaf/0.1/name": [ { "@value": "Markus Lanthaler" } ]
  }
]
```

PROPOSAL 1: Drop empty arrays (sets) when expanding

PROPOSAL 2: Drop empty lists when expanding

Lists are a bit special here since an empty list is actually a value. So it might make sense to keep them but drop empty sets.

**Comment by garpinc** [comment]
I am not understanding the resolution here. What if I do want empty lists to be turned into owl:Nothing? Is there I hook I can add to enable this translation?
