### ISSUE TITLE
Review of old normalization algorithm

### ISSUE THREAD

**Issue by msporny** [json-ld/json-ld.org#228]
From David Booth:

Regarding http://json-ld.org/spec/latest/rdf-graph-normalization/

I am delighted to see that people are working on this!  This will help fill a huge gap that we currently have.  A few small suggestions:

1. You really should reference Jeremy Carroll's original work on RDF canonicalization:
http://www.hpl.hp.com/techreports/2003/HPL-2003-142.pdf

2. I do not find the word "canonical" or "canonicalization" anywhere in the document, although it is clearly implied by the bnode prefix "c14n".  It is a stylistic choice whether to call the process "normalization" or "canonicalization".  In my observation, over the years "canonicalization" has been used more specifically for this process (as Jeremy Carroll's 2003 paper did), and hence would be the better choice of primary term.  But regardless of the choice, I think it is important to include both terms up front, to enable searchers to find it more easily.

3. The document contains an editorial note saying that the algorithm is obsolete.  Could you please point to the newer one?  Even if it is not yet finalized, it would be nice to be able to see what it is, whether it is just an email message, a snippet of code or whatever.  If you could point to pieces of working code -- even if they are not finished -- that would be great too.

Original e-mail: http://lists.w3.org/Archives/Public/public-linked-json/2013Mar/0009.html

**Comment by gkellogg** [comment]
Normalization has been moved to https://github.com/json-ld/normalization.
