### ISSUE TITLE
Ability to declare a container as both @index and @set

### ISSUE THREAD

**Issue by lrowe** [json-ld/json-ld.org#269]
I have the following indexed data structure that I'd like to preserve during compaction:

```
{
  "dbxref": {
    "db1": ["term1"],
    "db2": ["term2a", "term2b"]
  }
}
```

Declaring a context with @container: @index partly works, but I also want to preserve the array even when it has only a single member:

```
{
  "@context": {
    "@vocab": "http://localhost/context#",
    "dbxref": {
      "@container": "@index"
    }
  },
  "@id": "http://localhost/item1",
  "dbxref": {
    "db1": "term1",
    "db2": ["term2a", "term2b"]
  }
}
```

It would be helpful to have some way to declare a container as both @index and @set.

**Comment by gkellogg** [comment]
I propose taking this off of the 1.1 milestone; please 👍 or 👎.
