### ISSUE TITLE
Creating Linked Data from JSON is harder then expected

### ISSUE THREAD

**Issue by gcarothers** [json-ld/json-ld.org#271]
The hardest part of creating Linked Data from JSON is assigning URIs to specific parts of the JSON. In examples this is done by adding `@id` to specific parts of the JSON. In real world JSON there are often already IDs, however these IDs are NOT URIs, some method for turning them into URIs is required. Happily `@id` combined with `@base` works. HOWEVER, it only works as long as there is only a single kind of Resource that needs an URI. Some method of assigning URIs to Resources that are nested with, or coincident with the Resources of the other types. See comments for concrete examples.

**Comment by gkellogg** [comment]
Also see #426.

**Comment by gkellogg** [comment]
I propose closing this with no change; please 👍 or 👎.
