### ISSUE TITLE
Support JSON values that aren't mapped

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#333]
This has already been discussed several times usingvarious terms.. the most recent request has come from [David Janes on the mailing list](http://lists.w3.org/Archives/Public/public-linked-json/2014Mar/0010.html). The basic idea is to support JSON values/subtrees that aren't mapped to an IRI in the context. They should survive algorithmic transformations (basically without being touched at all).

**Comment by gkellogg** [comment]
Perhaps something like `@container: @literal` to treat it something like the way RDFa treats `rdf:XMLLiteral` or `rdf:HTML`. To support RDF transformations, it probably deserves its own datatype IRI.

**Comment by dlongley** [comment]
Might need to be more specific about the type of literal to allow for different types of processing/passthrough like: `@container: @json`.

**Comment by gkellogg** [comment]
See http://geojson.org/geojson-ld/ for a motivation for use in GeoJSON.

**Comment by gkellogg** [comment]
Thinking about this some more, it's important to consider the desired expanded representation. IMO, allowing values of `@value` to include objects and arrays (framing has some use of this now, so we need to be somewhat careful) is the natural way I would see data to be expanded, along with an appropriate datatype. For example:

```json
[{
  "@id": "http://exaple/foo",
  "http://example/json-value": [{
    "@value": [{"native": "json"}],
    "@type": "http://www.w3.org/ns/jsonld#JSON"
  }]
}]
```

This allows the JSON `{"native": "json"}` to be represented as the value of `http://example/json-value`. When compacted, it might look like the following:

```json
{
  "@context": {
    "@vocab": "http://example/",
    "@base": "http://example/",
    "jsonld": "http://www.w3.org/ns/jsonld#",
    "json-value": {"@type": "jsonld:JSON"}
  },
  "@id": "foo",
  "json-value": {"native": "json"}
}
```

Using `@container: @set` could be used to force the compacted version to be in array form.

Transforming to RDF would preserve the `jsonld:JSON` datatype, and perform a canonical JSON serialization of the content, deserializing when going back from RDF to JSON-LD. There may be implications for RDF L2V.

**Comment by niklasl** [comment]
For the record, as discussed in the call, we might consider supporting all possible JSON values (i.e. strings, booleans and numbers as well as objects and arrays).

**Comment by gkellogg** [comment]
[Discussed](https://json-ld.org/minutes/2018-02-26/#topic-5) on the call today:

> **RESOLUTION**: adopt solution defined in https://github.com/json-ld/json-ld.org/issues/333#issuecomment-366766394 as an interum solution, with final selection of the datatype to a future WG.

We may experement with using `@type: @json` to signal this, and leave the datatype IRI for the RDFa conversion.

**Comment by gkellogg** [comment]
Deferred to WG due to https://json-ld.org/minutes/2018-04-10/#resolution-3.

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/4.
