### ISSUE TITLE
Option to compact terms but not values

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#338]
**_This was raised by [Fabian Steeg](http://lists.w3.org/Archives/Public/public-linked-json/2014Mar/0033.html):**_

> The JSON-LD API document states: "Expansion has two important goals: removing any contextual information from the document, and ensuring all values are represented in a regular form."
> 
> Is there a way to achieve only the second goal, the regular form, but with compact terms? Using compaction with compactArrays=false is pretty close, but there is still at least one thing that is irregular and causing issues for me.
> 
> Given this input:
> 
> ```
> {
>   "http://example.com/foo": "foo-value",
>   "http://example.com/bar": {
>     "@value": "bar-value",
>     "@language": "en"
>   },
>   "@context": {
>     "foo": "http://example.com/foo",
>     "bar": "http://example.com/bar"
>   }
> }
> ```
> 
> I get this from compaction with compactArrays=false:
> 
> ```
> {
>   "@graph": [{
>     "foo": ["foo-value"],              <-- foo: array of strings
>     "bar": [{                          <-- bar: array of objects
>       "@language": "en",
>       "@value": "bar-value"
>     }]
>   }],
>   "@context": {
>     "foo": "http://example.com/foo",
>     "bar": "http://example.com/bar"
>   }
> }
> ```
> 
> But I'd like to get this (which is what expansion does to the values):
> 
> ```
> {
>   "@graph": [{
>     "foo": [{                          <-- both foo and bar:
>       "@value" : "foo-value"               array of objects
>     }],
>     "bar": [{
>       "@language": "en",
>       "@value": "bar-value"
>     }]
>   }],
>   "@context": {
>     "foo": "http://example.com/foo",
>     "bar": "http://example.com/bar"
>   }
> }
> ```
> 
> So I guess I'm looking for something like a compactValues=false option.
> 
> Is there some way to get this output?

**Comment by gkellogg** [comment]
Transfered to WG: https://github.com/w3c/json-ld-api/issues/3.
