### ISSUE TITLE
Framing only allows a single Context

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#356]
If a graph is expanded from multiple contexts and then compacted again, only a single context can be given and thus the original contexts are lost in the process, resulting in URIs for keys that had previously been much prettier strings.

The requirement comes from a multi-community use case, where there is a widely shared and implemented top level context and structure, but individual communities or institutions can, at prescribed points, include their own information in sub-trees with their own contexts.

An artificial example:
```json
{
  "@context" : "http://example.com/main/api/context.json",
  "main:key1" : "value",
  "main:extension" : {
    "@context" : "http://example.museum/extension/context.json",
    "ext:keyX" : "extension value"
  }
}
```

**Comment by gkellogg** [comment]
I think #315 already describes this, so this is a duplicate.
