### ISSUE TITLE
Lists shared between graphs are not correctly serialized

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#357]
**_[Reported](http://lists.w3.org/Archives/Public/public-rdf-comments/2014Jul/0011.html) by @afs:**_

We are encountering an issue when converting RDF Datasets to JSON-LD.

The problem is with blank nodes that are shared between graphs and lists.

In TriG (yes, this is a synthetic reduced test case that captures a 
smaller example that might appear for real):

```
# Bnode references across graph and lists
PREFIX :        <http://www.example.com/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

:G {
   # Written in short form it would be:
   # :z :q ("cell-A" "cell-B")
   # but we want to share the tail ("cell-B")

   :z :q _:z0 .

   _:z0   rdf:first "cell-A" .
   _:z0   rdf:rest  _:z1 .

   _:z1   rdf:first "cell-B" .
   _:z1   rdf:rest rdf:nil .
}

:G1 {
    # This references the tail  ("cell-B")
    :x :p _:z1 .
}
```

The triple in :G1 references into the list in :G.

But as we understand the conversion algorithm, section 4 only considers 
each graph in turn and so does not see the cross graph sharing.

Is this a correct reading of the spec text?

Part 4 of the conversion algorithm has
"For each name and graph object in graph map: "

so 4.3.3.\* walks back up the list in one graph only.

(Conversion generated by jsonld-java : it does not matter if compaction 
is applied or not):

```
{
   "@graph" : [ {
     "@graph" : [ {
       "@id" : ":z",
       ":q" : {
         "@list" : [ "cell-A", "cell-B" ]
       }
     } ],
     "@id" : ":G"
   }, {
     "@graph" : [ {
       "@id" : ":x",
       ":p" : {
         "@id" : "_:b1"
       }
     } ],
     "@id" : ":G1"
   } ],
   "@context" : {
     "@base" : "http://www.example.com/",
     "" : "http://www.example.com/",
     "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   }
}
```

There is no _:b1 in :G to refer to because the algorith generated @list 
and its implicit bNodes don't have labels.
This is a different dataset with no shared bNode.

If it is all the same graph (s/:G1/:G/), the RDF dataset structure is 
correctly serialized.

Andy

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-api/issues/13.

**Comment by gkellogg** [comment]
I agree with @dlongley that duplicates are handled by virtue of the RDF Dataset description, so the NQuads input would be normalized into a Dataset first, which would handle all triples. No need to duplicate this logic to deal with a serialization that may contain duplicates.
