### ISSUE TITLE
JSON-LD 1.1 Feature Request: Object-level @language

### ISSUE THREAD

**Issue by jasnell** [json-ld/json-ld.org#368]
See: https://github.com/digitalbazaar/jsonld.js/issues/72

It would be helpful to have the ability to use @language within an object as a shorthand for "@context": {"@language": "..."} ... for instance... make:

``` json
{
  "@language": "en",
  "displayName": "foo"
}
```

equivalent to:

``` json
{
  "@context": {"@language": "en"}, 
  "displayName": "foo"
}
```

**Comment by kevinSuttle** [comment]
Would something like http://formatjs.io/ help out here?

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/5.
