### ISSUE TITLE
JSON-LD 1.1 Feature Request: Term-level @base / @vocab

### ISSUE THREAD

**Issue by jasnell** [json-ld/json-ld.org#369]
In certain cases, it would be helpful to have the ability to specify term-level @vocab or @base in the @context. For instance:

``` json
{
  "@context": {
    "as": "urn:example:",
    "foo": {
      "@id": "as:foo",
      "@type": "@vocab",
      "@vocab": "urn:legacy:"
    }
  },
  "foo": "bar"
}
```

When processed, "foo": "bar" expands to "urn:example:foo": "urn:legacy:bar"

The motivating case for this is the migration of Activity Streams 1.0 to 2.0. In AS1, certain properties (verb and objectType) are allowed to be either simple tokens OR fully qualified IRIs. With the simple token, the values do not expand out to IRIs. With the current approach, these would end up expanding to whatever the in-scope Base URL is, which is problematic. What we need is the ability to reliably handle arbitrary token values in a predictable way without requiring that each value be predefined in a context or requiring modifications to the original JSON. The ability to declare a term-level @vocab or @base URI would provide exactly what is needed to address the issue.

**Comment by elf-pavlik** [comment]
:+1:

**Comment by neothemachine** [comment]
I just wondered why that's not working in the playground, seems very natural to do. Another example:
```js
{
  "@context": {
    "standard_name": {
      "@id": "http://../standard_name",
      "@type": "@vocab",
      "@vocab": "http://vocab.nerc.ac.uk/standard_name/"
     }
  },
  "standard_name": "sea_ice_temperature"
}
```

I see this not just important for legacy JSON documents but also for new ones where you just don't want to deal with URLs in some places.

**Comment by kevinSuttle** [comment]
+1. Are there docs for the "`as`" keyword you used? There is a similar pattern in EcmaScript 6. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by kevinSuttle** [comment]
Also, I had played around with this, which felt a little more natural

```jsonld
{
  "@context": "https://schemas.acme.com",
  "@type": "brand",
  "name": "RS,
  "fullName": "RocketSkates",
  "isPartOf": "@context/brands",
  "version": "0.1.0",
  "colorPalette": "@context/brands/rocketskates/colors",
  "logos": "@context/brands/rocketskates/logos"
}
```

It could be that there is a tree-parser that treats short values as paths relative to `@context` URLs, eliminating the need for repeat `@context` references.

**Comment by elf-pavlik** [comment]
> +1. Are there docs for the "as" keyword you used?

`as:` gets used just as a normal [CURIE](http://www.w3.org/TR/curie/) prefix, doesn't make difference here but James works on Activity Streams vocab http://prefix.cc/as

> ```
{
  "@context": "https://schemas.acme.com",
  "@type": "brand",
  "name": "RS",
  "fullName": "RocketSkates",
  "isPartOf": "@context/brands",
  "version": "0.1.0",
  "colorPalette": "@context/brands/rocketskates/colors",
  "logos": "@context/brands/rocketskates/logos"
}
```

I really don't understand what you try to do here, can you please provide expected JSON-LD [expended version](http://www.w3.org/TR/json-ld/#expanded-document-form) of your snippet ? Possibly also relevant part of `@context` you want to use.

**Comment by neothemachine** [comment]
One more motivational example:
```js
"@context": {
  "refPeriod": {
    "@id": "http://purl.org/linked-data/sdmx/2009/dimension#refPeriod",
    "@type": "@id",
    "@vocab": "http://reference.data.gov.uk/id/gregorian-interval/"
  }
},
"refPeriod": "2004-01-01T00:00:00/P3Y",
```
