### ISSUE TITLE
JSON-LD 1.1 Feature Request: New @label keyword

### ISSUE THREAD

**Issue by jasnell** [json-ld/json-ld.org#371]
In the spirit of "Labeling Everything" (http://patterns.dataincubator.org/book/label-everything.html) ... it would be worthwhile, IMO, for JSON-LD to provide a basic @label keyword for use both in @context and nodes. It's largely syntactic sugar but would be useful. 

For example:

``` json
{
  "@context": {
    "@label": "An Example Context",
    "displayName": "@label",
  },
  "displayName": "A Simple Label"
}
```

Which would expand to:

```
_:c14n0 <http://www.w3.org/2000/01/rdf-schema#label> "A Simple Label" .
```

**Comment by kevinSuttle** [comment]
See also: https://github.com/json-ld/json-ld.org/issues/369#issuecomment-168830287

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/6.
