### ISSUE TITLE
Add GitHub milestone 1.1

### ISSUE THREAD

**Issue by akuckartz** [json-ld/json-ld.org#373]
That seems to be more appropriate than a label.

**Comment by davidlehn** [comment]
@gkellogg: What's going on with this? It appears the 1.1 issues are getting both a 1.1 label and the JSON-LD.next milestone. It might be easier to only use milestones for this sort of tracking. Sorry I started the labeling. :-)  How about renaming "JSON-LD.next" to "JSON-LD 1.1" and just using that?

**Comment by gkellogg** [comment]
That's probably a good idea.
