### ISSUE TITLE
Inconsistency between Syntax and API specs

### ISSUE THREAD

**Issue by dlongley** [json-ld/json-ld.org#375]
The [JSON-LD Syntax spec](http://www.w3.org/TR/json-ld/#language-maps) indicates that the values of keys in a language map may be `null`. However, the [Expansion Algorithm](http://www.w3.org/TR/json-ld-api/#expansion-algorithm) raises an error if a value is not a string (therefore not allowing `null`). See:

```
7.5.2.2.1) item must be a string, otherwise an invalid language map value error has been detected and processing is aborted.
```

Similarly, the [invalid language map value error definition](http://www.w3.org/TR/json-ld-api/#idl-def-JsonLdErrorCode.invalid-language-map-value) in the API spec doesn't mention allowing `null`.

@lanthaler, @gkellogg, @msporny -- thoughts on the proper resolution? Which spec do you think is incorrect?

I believe we have no tests for using `null` values in a language map -- and if I modify `jsonld.js` to allow `null`, no other tests fail.

Related to https://github.com/digitalbazaar/jsonld.js/issues/76.

**Comment by dlongley** [comment]
This seems to be a problem on Step 7.4.7 as well.

**Comment by dlongley** [comment]
I resolved this in [jsonld.js](https://github.com/digitalbazaar/jsonld.js) by just dropping the `@language` property when expanding (if its value is `null`). This is the same effect, I believe, setting `@language` to null would have (no `@language` is the same as `@language: null` when in expanded form).

**Comment by nichtich** [comment]
This bug had not been fully fixed yet, try this test case:

```json
{
  "@context": { "f:foo": { "@container": "@language" } },
  "f:foo": { "en": "foo", "fr": null }
}
```

The `null` value should be ignored instead of throwing an error.

**Comment by gkellogg** [comment]
@dlongley Step 7.4.7 requires that the value of `@language` be a string, which is consistent with the [grammar rule in JSON-LD 1.1](https://www.w3.org/TR/2014/REC-json-ld-20140116/#value-objects):

> The value associated with the `@language` key **must** have the lexical form described in [BCP47], or be **null**.

I'm not sure any changes is indicated there. Perhaps, if there are algorithms which can emit **null** `@language`, they should not.

**Comment by dlongley** [comment]
Maybe I'm just too tired right now and I'm missing something, but since the grammar rule says the value can be `null`, don't we have to allow for that in Step 7.4.7 as a possible valid input?

**Comment by gkellogg** [comment]
I read the grammar as allowing the value of a language map to be null, which would turn into the @value of the value object. The value of @language must be a string compatible with BCP. This would translate to the key of a language map.
