### ISSUE TITLE
Update framing spec to use new embed API

### ISSUE THREAD

**Issue by dlongley** [json-ld/json-ld.org#377]
A new experimental embed API has been implemented in jsonld.js. Instead of using `"@embed": true/false`, three options for the `@embed` directive are available: `@always`, `@never`, and `@last`. The current framing behavior for `"@embed": true` matches that of `@last` which is the default. There's backwards compatibility support in jsonld.js for the previous `@embed` boolean flags.

I think this is a pretty good way forward for more powerful embedding w/framing. I recently simplified parts of the framing algorithm in jsonld.js related to embedding as well -- so I decided to make an issue here for tracking the need to update the framing spec. I think when we do an update, we should include this new API and we can look at the jsonld.js implementation to help simplify the algorithm prose. Thoughts?

See: https://github.com/digitalbazaar/jsonld.js/pull/68

Addresses: #119.

**Comment by kevinSuttle** [comment]
@dlongley This is fascinating. I would love to hear your thoughts on how something like this would work on the effort currently underway: https://github.com/schemaorg/schemaorg/issues/created_by/kevinSuttle

**Comment by kevinSuttle** [comment]
Also, is this issue still open? Looks like https://github.com/digitalbazaar/jsonld.js/pull/68 is closed and https://github.com/json-ld/json-ld.org/issues/119 probably should be.

**Comment by lanthaler** [comment]
Yes, this issue is still open. We aren’t working on the specs at the moment.

**Comment by gkellogg** [comment]
This is addressed in 5a3e50610ef7c1fc08f92a2a5b393ab9741c0c11. However, I think there's more room for discussion on @embed, and order dependency in general.
