### ISSUE TITLE
TurtleRDFParser throws exception on valid ttl

### ISSUE THREAD

**Issue by chile12** [json-ld/json-ld.org#382]
using v 2.5.0

When parsing a ttl file i get the following parse error:
Error while parsing Turtle; missing expected "]" "," ";" or ".". {line: 37position: 2}

which referrers to a missing closing bracket of a blank node.

here the corresponding lines:

33  dcat:contactPoint [
34    a dataid:Agent ;
35    rdfs:label "Magnus Knuth" ;
36    foaf:name "Magnus Knuth" ;
37    foaf:mbox "magnus.knuth(at)hpi.uni-potsdam.de"
38  ] ;

The file parses correctly when using sesame-rio-turtle 2.8.0.

Any suggestions or work around?

**Comment by davidlehn** [comment]
Is this a JSON-LD issue?  Perhaps this issue should be moved to another project?

**Comment by elf-pavlik** [comment]
@chile12 I guess you use JSON-LD Java not JSON-LD Javascript
https://github.com/jsonld-java/jsonld-java/blob/ef63e515c3801821e8f656516fb77b3c10182978/core/src/test/java/com/github/jsonldjava/impl/TurtleRDFParserTest.java
