### ISSUE TITLE
Processing model for context conflicts

### ISSUE THREAD

**Issue by dret** [json-ld/json-ld.org#391]
i may simply be using the wrong keyword ("conflict"), but when looking for how JSON-LD deals with conflicting definitions in contexts, i couldn't easily find an answer. it may be interesting alone to look at this in the context of inline and referenced contexts.
but more and more, people are defining implicit contexts (https://github.com/jasnell/w3c-socialwg-activitystreams/issues/132 is one example where we are trying to figure out what *exactly* this means in all possible cases), trying to make things easier by defining that consumers should assume a context to be there even though it is neither inlined nor referenced. is there a well-defined processing model for this, so that in such a scenario it is clear what happens if there are conflicts between the implicit context, and context info that may be explicitly inlined or referenced in the JSON?

**Comment by jasnell** [comment]
In the case of AS2, it should be pointed out that the implicit context is only assumed if (a) an explicit context is not provided using established JSON-LD mechanisms and (b) the application/activity+json media type is used. Given that, dealing with potential conflicts becomes much easier. Explicit always overrules implicit.

**Comment by dret** [comment]
thanks @jasnell, and maybe i am just imagining things. it just seems to me that if we see this pattern emerging, maybe having a well-defined processing model (when to use which context, and how to deal with conflicts in the inline/referenced/implicit cascade) maybe be something that may be useful in itself, and not just as something that each service has to define separately, then we could even hope that at some point, libraries might start supporting this kind of processing.

**Comment by msporny** [comment]
The JSON-LD processing rules are very clear about what happens:

http://www.w3.org/TR/json-ld/#advanced-context-usage
"Duplicate context terms are overridden using a most-recently-defined-wins mechanism."

**Comment by msporny** [comment]
@jasnell You /could/ specify in the AS2 spec that in the event that @context isn't specified, a "@context": "https://as.example.com/contexts/v1" should be injected into the document before any JSON-LD processing occurs.

That would change the "implicit" bit to something a bit more clear to developers.

**Comment by lanthaler** [comment]
As Manu already said, the spec is very clear about this. Erik, a quick reply to your comment that 

> it may be interesting alone to look at this in the context of inline and referenced contexts.

From a processing perspective remote and inline contexts are exactly the same. So there's nothing particularly interesting about that case. What did you have in mind?

> [AS is] trying to make things easier by defining that consumers should assume
> a context to be there even though it is neither inlined nor referenced

Is that the reason? I can't see how that simplifies things for users. None of the existing JSON-LD tools can work with it without workarounds. But that discussion probably belongs in the referenced issue, not here.

**Comment by dret** [comment]
@msporny, "most-recently-defined-wins" assumes that a referenced context is less recent than any inline context, right? then maybe the interesting question is: is an implicit context more or less recent than an external one? if you define it as "injected into the document", it wins over an external one, right?

**Comment by dret** [comment]
@lanthaler, afaict, the AS2 motivation is to allow producers to completely ignore the fact that JSON-LD exists, but still make that plain JSON consumable for those that want to work with an RDF view.

**Comment by lanthaler** [comment]
> "most-recently-defined-wins" assumes that a referenced context is less recent than any inline context, 

Referenced from where? If you have an array of contexts (mixture of embedded ones and links to remote contexts) you process them in the order that they appear in the array. If they are in different places in the document, you process them in the order they appear from the root element down the leaf element (nested objects etc.) Contexts referenced via the HTTP Link header are ignored for `application/ld+json` documents; for other `+json` media types and `application/json` it is the first process being processed.

> right? then maybe the interesting question is: is an implicit context more or less recent than an external one?

JSON-LD doesn't have a notion of "implicit context" thus I can't answer this question. That being said, the JSON-LD API allows to pass an expandContext as an option. Such a context will be processed before anything else (http://www.w3.org/TR/json-ld-api/#idl-def-JsonLdOptions).

 if you define it as "injected into the document", it wins over an external one, right?
