### ISSUE TITLE
Named graph inside default graph

### ISSUE THREAD

**Issue by letmaik** [json-ld/json-ld.org#398]
I'd like to include metadata/control data in a non-default graph (see [this blog post](http://ruben.verborgh.org/blog/2015/10/06/turtles-all-the-way-down/)) and doing so could be more seamless in my mind.

A simple example: Imagine you want to add pagination functionality to an API that serves GeoJSON(-LD) feature collections like `places.geojson?page=n`. Let's say the collection has 1Mio elements and you want to deliver 10000 features per page. And the navigation information should be included in the document as metadata ("next" page, "previous" page, "first", "last", "total feature count"). The client would then understand that. However, you don't want to include that navigation metadata as actual "data" in the default graph but instead put it in a separate graph. My current solution (based on [hydra pagination](https://www.w3.org/community/hydra/wiki/Pagination)):

``` js
{
  "@context": [
    "https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld",
    {
      "hydra": "http://www.w3.org/ns/hydra/core#",
      "view": "hydra:view",
      "PartialCollectionView": "hydra:PartialCollectionView",
      "previous": "hydra:previous",
      "next": "hydra:next"
    }
  ],
  "id": "http://example.com/places",
  "type": "FeatureCollection",
  "features": [{
    "id": "foo"
  }, {
    "id": "bar"
  }],
  "view": {
    "id": "#pagination",
    "@graph": {
      "id": "http://example.com/places?page=3",
      "type": "PartialCollectionView",
      "previous": "http://example.com/places?page=2",
      "next": "http://example.com/places?page=4"
    }
  }
}
```

(GeoJSON-LD's context aliases id/type)

But what I'd really like is the following:

``` js
{
  "@context": [
    "https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld",
    {
      "hydra": "http://www.w3.org/ns/hydra/core#",
      "view": {"@id": "hydra:view", "@graph": {"@id": "#pagination"}},
      "PartialCollectionView": "hydra:PartialCollectionView",
      "previous": "hydra:previous",
      "next": "hydra:next"
    }
  ],
  "id": "http://example.com/places",
  "type": "FeatureCollection",
  "features": [{
    "id": "foo"
  }, {
    "id": "bar"
  }],
  "view": {
    "id": "http://example.com/places?page=3",
    "type": "PartialCollectionView",
    "previous": "http://example.com/places?page=2",
    "next": "http://example.com/places?page=4"
  }
}
```

Does that make sense?

**Comment by dlongley** [comment]
> Does that make sense?

Yes. We have a similar use case where we need to embed digitally-signed graphs of information into the default graph. We've been exploring something like a `"@container": "@graph"` feature (this if for unlabeled non-default graphs).

I'd like to see something added to JSON-LD for these cases.

**Comment by gkellogg** [comment]
This is similar to what was requested in #247, #262, #369, and #397.

In general, there is strong support for adding information to term definitions that affects subsequent processing. They all create challenges when trying to use this for compacting otherwise expected JSON-LD, but this might be relaxed in the future.

**Comment by gkellogg** [comment]
For this to work, I think we need a combination of expanding the range of `@container` to `@graph`, and either an array form like `[@graph, @set]` or something like `@graphSet`. The `@content` (from #247 and #426) could then assert the `@id` of that graph, but would still require some explicit layers in the asserted JSON. Elaborating on @letmaik's proposed solution:

```json
{
  "@context": [
    "https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld",
    {
      "hydra": "http://www.w3.org/ns/hydra/core#",
      "view": {"@id": "hydra:view", "@container": "@graph", "@graphId": "#pagination"},
      "PartialCollectionView": "hydra:PartialCollectionView",
      "previous": "hydra:previous",
      "next": "hydra:next"
    }
  ],
  "id": "http://example.com/places",
  "type": "FeatureCollection",
  "features": [{
    "id": "foo"
  }, {
    "id": "bar"
  }],
  "view": {
    "id": "http://example.com/places?page=3",
    "type": "PartialCollectionView",
    "previous": "http://example.com/places?page=2",
    "next": "http://example.com/places?page=4"
  }
}
```

The `@graphId` is allowed within a term definition if `@container` is `@graph`. `@graph` might have the value of an object, if there's only one value, or an array of objects, otherwise. The use of `["@graph", "@set"]` or `@graphSet` might be used to enforce the value to be an array.

**Comment by gkellogg** [comment]
I propose taking this off of the 1.1 milestone; please 👍 or 👎 to favor/disfavor removing.

**Comment by gkellogg** [comment]
Duplicates #481 and #195.
