### ISSUE TITLE
List of things

### ISSUE THREAD

**Issue by davideicardi** [json-ld/json-ld.org#401]
In our application we need to implement some mechanism to import external entities (we need to import and use in our system a list of external defined things, like "events", "athletes", "cities", "stadiums", ...).

Looking around the web I came across json-ld. So instead of defining our importing format we are thinking about just saying that we support any json-ld document/api. This sound great!

But I have a problem...

I cannot find a "standard" way to define list of things. I found a lot of ways of doing the same:

- `@list` or `@set` keywords
- plain json arrays
- schema.org `DataFeed` type, [see here](http://schema.org/DataFeed) or similar 
- someone just use the `@graph` notation (like [dbpedia](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=DESCRIBE+%3Chttp://dbpedia.org/resource/The_Beatles%3E&output=application%2Fld%2Bjson))
- or there is also the Hydra `Collection`, [see here](http://www.hydra-cg.com/spec/latest/core/#collections)

How do you suggest to implement our import solution? 
If I was a publisher I probably love this flexibility but as a consumer I'm a little puzzled ...

Of course we can eventually support more than one solution but we prefer to choose one single implementation and require our customers to use this format.
Is JSON-LD a good choice?

**Comment by lanthaler** [comment]
I'm closing this issue as it is not a JSON-LD issue. @davideicardi if you want to discuss this further, feel free to post on public-linked-json@w3.org or public-hydra@w3.org There are lots of very knowledgeable people on that list that are happy to help.
