### ISSUE TITLE
Relax the colliding keywords constraint for @type

### ISSUE THREAD

**Issue by letmaik** [json-ld/json-ld.org#402]
I want the following:

``` js
{
  "@context": {
    "type": "@type",
    "profile": "@type"
  },
  "type": "cov:Coverage",
  "profile": "cov:GridCoverage"
}
```

However this is not allowed. The playground says "Invalid JSON-LD syntax; colliding keywords detected".

However, this one works:

``` js
{
  "@context": {
    "type": {"@id": "rdf:type", "@type": "@id" },
    "profile": {"@id": "rdf:type", "@type": "@id" }
  },
  "type": "cov:Coverage",
  "profile": "cov:GridCoverage"
}
```

I understand that this restriction probably makes sense for other keywords, but could it do any harm for `@type`?

**Comment by gkellogg** [comment]
Transfered to the WG: https://github.com/w3c/json-ld-api/issues/4.

**Comment by azaroth42** [comment]
@letmaik Would scoped contexts resolve your use case without relaxing the collision constraint? Or is it that you have existing JSON that you want to map to RDF and there are two fields that both map to `rdf:type` / `@type`?
