### ISSUE TITLE
JSON-LD 1.1 Feature Request: Prefer simple terms to complex terms when creating Compact IRIs.

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#405]
As mentioned in #404, JSON-LD IRI compaction to Compact IRI representations can generate non-desirable results.

Take, for example, the following JSON-LD context (abbreviated from the actual schema.org context):

``` json
{
  "@context": {
    "schema": "http://schema.org/",
    "sport": { "@id": "http://schema.org/sport", "@type": "@id" }
  }
}
```

Then, compact the following:

``` json
[{
  "http://schema.org/sportsEvent": {"@id": "http://example.com/event"}
}]
```

What you get is the following:

``` json
{
  "@context": {
    "schema": "http://schema.org/",
    "sport": {
      "@id": "http://schema.org/sport",
      "@type": "@id"
    }
  },
  "sport:sEvent": {
    "@id": "http://example.com/event"
  }
}
```

when, what is expected is:

``` json
{
  "@context": {
    "schema": "http://schema.org/",
    "sport": {
      "@id": "http://schema.org/sport",
      "@type": "@id"
    }
  },
  "schema:sportsEvent": {
    "@id": "http://example.com/event"
  }
}
```

The reason for this is that the compactIri algorithm looks for the shortest Compact IRI.

This was addressed in the [Ruby JSON-LD gem](http://github.com/ruby-rdf/json-ld) in https://github.com/ruby-rdf/json-ld/commit/c8760e2177c286f3fdc72e3bb2373bb406cc5520 by adding a `simple_compact_iris` option. This uses the concept of a **simple term definition** (i.e., a [term definition](http://www.w3.org/TR/json-ld/#dfn-term-definition) which is not an [expanded term definition](http://www.w3.org/TR/json-ld/#dfn-expanded-term-definition)) and favors a **simple term definition** over an **expanded term definition** when creating a Compact IRI. With this option, step 5 of the [IRI Compaction Algorithm](http://www.w3.org/TR/json-ld-api/#iri-compaction) is modified:

> For each key _term_ and value _term definition_ **which is a _simple term definition_** in the active context:

An alternative would be to make two passes, one using **simple term definition** and the next, if no compact IRI is generated, using **expanded term definitions**.

**Comment by gkellogg** [comment]
@azaroth42, as you may be using the Ruby JSON-LD gem, you might try using the `simple_compact_iris` option when compacting and/or framing to see if that helps your immediate use case.

**Comment by gkellogg** [comment]
As discussed in #469, this is more broadly a problem for expanding properties where a term may mask a URI scheme. So, the proposal is more concretely the following:

# When compacting:
Only simple terms may be used for creating Compact IRIs, where those terms have any of the following properties:
* The term ends with ":", or
* The value of the term is an IRI ending with a "/" or "#"

# When expanding
A value which is treated as an IRI (either the value of `@id`, or the value of a property who's term is defined with `@type: @id` or `@type: @vocab`) is considered a Compact IRI if all of the following are true:
* The form of the value is a compact IRI represented as a prefix:suffix combination,
* The prefix is a term definition subject to the constraints described for selection in creating a Compact IRI as defined above, and
* The suffix does not begin with two slashes (//).

These restrictions must be followed by 1.1 processors when the processing mode is set to json-ld-1.1.

Optionally, 1.0 processors, or 1.1 processors when the mode is json-ld-1.0 may want to impose these restrictions presuming that doing so does not invalidate any JSON-LD 1.0 test-suite test.

**Comment by niklasl** [comment]
I think this would be quite prudent.

I do wonder if the IRI value for the term could be allowed to end in a couple more (or all) of the delims from RFC 3987? Although, if I understand correctly, your proposal also allows for something like:

    "pfx:": "urn:x-org:stuff:"

(Which would have `pfx:term` expand to `urn:x-org:stuff:term`.)

That would certainly be a solution for edge-cases ending in anything else. I guess it does complicate expansion a bit though, as you say: *with appropriate matching for terms ending with ":"*. I.e. the prefix to be used should be the value *before* the ending ":", right? I'm just pointing it out for all to factor in into consideration. I still think I'm in favor of it.

However, if that part wouldn't fly, we should consider including possibly all of the IRI gen-delims and sub-delims. While most (all?) vocabularies we know of end with "/" or "#", perhaps ":", "?" and "=" are possible (albeit special-purpose) endings. After all, this would be a new kind of restriction, and we don't wan't to close the door too tightly... (Having said that, I'm sure in a couple of years a case will crop up where the ending is of some other kind, like "term-" or "ns"...)

In any case, I do think we should seriously consider this.

**Comment by gkellogg** [comment]
> I do wonder if the IRI value for the term could be allowed to end in a couple more (or all) of the delims from RFC 3987?

We could, but I'm really not aware of cases where something other than "/" or "#" are used for RDF prefix expansions; it would allow for other use-cases, though. What did you have in mind?

> if I understand correctly, your proposal also allows for something like:

```
"pfx:": "urn:x-org:stuff:"
```

> (Which would have pfx:term expand to urn:x-org:stuff:term.)

Yes.

> That would certainly be a solution for edge-cases ending in anything else. I guess it does complicate expansion a bit though, as you say: with appropriate matching for terms ending with ":". I.e. the prefix to be used should be the value before the ending ":", right? I'm just pointing it out for all to factor in into consideration. I still think I'm in favor of it.

I don't think it's that complicated. "If _active context_ contains a _term definition_ (_term_) for _prefix_, or matching _prefix_ followed by a ":", return the result of concatenating the _IRI mapping_ associated with that term and _suffix_.

Compaction shouldn't be too much more difficult.

**Comment by VladimirAlexiev** [comment]
As far as I can grok (but grokking at 3am is not my strong suit), the above is a very constructive proposal and will fix https://github.com/json-ld/json-ld.org/issues/469 (clobbering of `geo:` and `tel:`). jsonld 1.1 it is!

To avoid props that are conflicted between two contexts, a dev should use a "full" term, eg `schema:geo` vs `vcard:geo`. Sounds ok.

**Comment by VladimirAlexiev** [comment]
Will this also fix the problem of "prefer shorter prefixes". Eg see http://json-ld.org/playground/#/gist/560ccf3285deb45f716689201b3c2c5d: 
Given
```
  "aat": "http://vocab.getty.edu/aat/",
  "aat_term": "http://vocab.getty.edu/aat/term/",
```
I'd prefer http://vocab.getty.edu/aat/term/1000018398-es to get shortened to
`aat_term:1000018398-es` but currently it's shortened to `aat:term/1000018398-es`

**Comment by gkellogg** [comment]
I implemented this in my processor, favoring simple terms ending in ':' over simple terms ending in a gen-delim, and not considering expanded terms. This breaks one existing test compact-0038-in.jsonld, which is really testing for index map round-tripping. So, for example terms would be generated like "title:/value" previously, and now are "site-cd:node/article/title/value", which actually makes more sense to me.

Basically, step 5 in the IRI Compaction algorithm is duplicated. On the first pass, if processing mode is 1.1, only simple terms ending in ':' are considered, and _compact IRI_ is created without add ing a colon. The second pass is modified to only consider simple terms (not expanded terms), and will only be considered if a _compact IRI_ was not generated in the previous pass.

IMO, it's acceptable to break this one test, and perhaps a 1.0 errata should restrict term selection for terms that aren't simple in any case.

See my implementation referenced above. If this is generally acceptable, I'll write it up, along with the update to #468, which already has commits in the https://github.com/json-ld/json-ld.org/tree/issue-405-468 branch.
