### ISSUE TITLE
How can JSON-LD integrate with GraphQL?

### ISSUE THREAD

**Issue by kevinSuttle** [json-ld/json-ld.org#409]
See context https://github.com/graphql/graphql-js/issues/271 and if you're new to GraphQL: https://learngraphql.com/basics/introduction

**Comment by kevinSuttle** [comment]
cc @msporny @dlongley @davidlehn

**Comment by davidlehn** [comment]
This is a rather open ended question.  Did you have specific use cases in mind?  You mention some features in the other issue but not what you want to do with them.

**Comment by gkellogg** [comment]
Closing without prejudice, as the referenced GraphQL issue has, itself, been closed.

**Comment by ppKrauss** [comment]
GraphQL is a new JSON-taste for an old initiative and standard language, that born in the 1970s with SQL: [Query by Example (QBE)](https://en.wikipedia.org/wiki/Query_by_Example).

There are a new promise-oriented JSON-taste QBE,  **JSON-LD-framing**. <br/>See https://json-ld.org/spec/latest/json-ld-framing/ 

PS: the GraphQL specification not cited QBE, and JSON-LD-framing specification not cite GraphQL or a QBE-reference... But there is great affinity between them.
