### ISSUE TITLE
How to detect error for non-JSON content type responses?

### ISSUE THREAD

**Issue by ariutta** [json-ld/json-ld.org#410]
I am looking at [this test](https://github.com/json-ld/json-ld.org/blob/b2c57989c1d72faf5d6fe788c0523120d8098136/test-suite/tests/remote-doc-manifest.jsonld#L34) that is supposed to give an error for non-JSON content type responses, but since the response comes back as `200 OK`, is the client code supposed to check that the response content type matches the request `Accept` header?

```
curl -X GET -i http://json-ld.org/test-suite/tests/remote-doc-0004-in.jldte -H "Accept: application/ld+json, application/json"
```
gives `HTTP/1.1 200 OK`

But
```
curl -X GET -i http://www.w3.org -H "Accept: application/ld+json"
```
gives `HTTP/1.1 406 Not Acceptable`

**Comment by gkellogg** [comment]
Yes, the only reliable way to test the response type is to use 'Content-Type'. The test ensures that the Content-Type is returned as `application/jldTest`, which won't match. Any way you want to check for this is fine, either by using Accept and getting a 406, or by inspecting the returned Content-Type. That is probably more generally applicable across different servers.

**Comment by ariutta** [comment]
I can't seem to find where this check is happening in the Javascript
client. Should I open an issue on that repo?

**Comment by lanthaler** [comment]
The relevant part in the spec can be found here: https://www.w3.org/TR/json-ld-api/#widl-JsonLdProcessor-compact-Promise-any-input-JsonLdContext-context-JsonLdOptions-options

**Comment by ariutta** [comment]
The spec says "If the input has been retrieved, the response has an HTTP Link Header...", but the headers received when requesting http://json-ld.org/test-suite/tests/remote-doc-0004-in.jldte do not include a Link Header:

```
HTTP/1.1 200 OK
date: Thu, 04 Feb 2016 22:12:53 GMT
server: Apache/2.2.22 (Ubuntu)
last-modified: Tue, 03 Sep 2013 22:21:00 GMT
etag: "20d76-0-4e5821a834bf9"
accept-ranges: bytes
content-length: 0
keep-alive: timeout=5, max=100
connection: close
content-type: application/jldtest
```

Is the Link Header supposed to be actually returned?

The reason I ask is that I don't understand how [this JS code](https://github.com/digitalbazaar/jsonld.js/blob/e63baf5efb394b327ce7eff8e079df6cd87e9d0a/js/jsonld.js#L1790) passes [this test](https://github.com/json-ld/json-ld.org/blob/b2c57989c1d72faf5d6fe788c0523120d8098136/test-suite/tests/remote-doc-manifest.jsonld#L34). There's nothing verifying that the response content type is correct.

**Comment by lanthaler** [comment]
You probably want to open a separate issue on jsonld.js' repo. This one here is about the JSON-LD specification in general - not specific implementations thereof.

**Comment by ariutta** [comment]
Closed in favor of https://github.com/digitalbazaar/jsonld.js/issues/129
