### ISSUE TITLE
vocabulary term variants

### ISSUE THREAD

**Issue by lisp** [json-ld/json-ld.org#412]
the context "event.jsonld" uses terms from a wgs84_pos vocabulary :

    "latitude": "http://www.w3.org/2003/01/geo/wgs84_pos#latitude",
    "longitude": "http://www.w3.org/2003/01/geo/wgs84_pos#longitude",
    "elevation": "http://www.w3.org/2003/01/geo/wgs84_pos#altitude",

that document defines "lat", "long" and "alt".

**Comment by davidlehn** [comment]
Thanks. Fixed.
https://github.com/json-ld/json-ld.org/commit/c2ca8bdab1a9e92ae833a1a164a51afa31a32115
