### ISSUE TITLE
how to handle the "@coerce"  key?

### ISSUE THREAD

**Issue by lisp** [json-ld/json-ld.org#413]
the `@coerce` key is present among the example contexts.
what is the proper way to handle that situation: warn and ignore or reject?

**Comment by gkellogg** [comment]
The section on [Node Objects](https://www.w3.org/TR/json-ld/#node-objects) says that all keywords other than, @context, @id, @graph, @type, @reverse and @index are to be ignored. There may be language about issuing a warning, but I don't recall anything specific. Note that JSON-LD Framing uses other keywords that are not ignored, but these are part of the framing model.

I would say that processors would ignore @coerce, and _may_ issue an warning, but _should not_ fail with an error, as this is a reasonable target for future standards work.

**Comment by lisp** [comment]
the general node case is less a cause for concern that the situation where "unknown" keywords appear in a context, as is the in several of those still in the repository.

**Comment by gkellogg** [comment]
If used as a term definition, a JSON-LD processor will happily create a term starting with `@`. Otherwise, if used as part of a term definition, it will be ignored.

If used as the value of `@container` it would be an error, unless one of `@list @set @language @index`.

**Comment by lisp** [comment]
that reads like a recipe for inexplicably incomplete results and unnecessary confusion.

the particular motivating case is

    https://github.com/json-ld/json-ld.org/blob/master/contexts/event.jsonld#L30

a sort of anomaly which brings up the question, how a step which intends to construct a context should handle something like 
    {
       "@content":
       {
    ... } ... }

**Comment by gkellogg** [comment]
A 1.0 processor will ignore it, as the object value isn't a void term definition.

**Comment by gkellogg** [comment]
Also, note that https://github.com/json-ld/json-ld.org/blob/master/contexts/event.jsonld#L30 is certainly an invalid context, and may be part of an experiment in how geo data might be handled. I think the action is to clean up this example and make sure it's valid. Perhaps as part of support for #397.

**Comment by niklasl** [comment]
`@coerce` was an old design (long before 1.0) for `@type` corecion. I'd say its legacy noise to be removed from the examples.

**Comment by gkellogg** [comment]
Looks like the context files are referenced from old drafts still available within the Previous Drafts section; removing and/or modifying them would be re-writing history.
