### ISSUE TITLE
Compaction of language maps with @value aliased not as expected

### ISSUE THREAD

**Issue by neothemachine** [json-ld/json-ld.org#420]
```js
{
  "@context": {
    "id": "@id",
    "type": "@type",
    "value": "@value",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "label": { "@id": "skos:prefLabel", "@container": "@language" },
    "qudt": "http://qudt.org/schema/qudt#",
    "symbol": "qudt:symbol",
    "UCUM": "http://www.opengis.net/def/uom/UCUM/"
  },
  "id": "qudt:DegreeCelsius",
  "label": {"en": "Degrees Celsius"},
  "symbol": {
    "type": "UCUM",
    "value": "Cel"
  }
}
```

When I compact that with the same context I get:
```js
{
  "@context": {
    "id": "@id",
    "type": "@type",
    "value": "@value",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "label": {
      "@id": "skos:prefLabel",
      "@container": "@language"
    },
    "qudt": "http://qudt.org/schema/qudt#",
    "symbol": "qudt:symbol",
    "UCUM": "http://www.opengis.net/def/uom/UCUM/"
  },
  "id": "qudt:DegreeCelsius",
  "symbol": {
    "type": "UCUM",
    "value": "Cel"
  },
  "label": {
    "en": {
      "@language": "en",
      "value": "Degrees Celsius"
    }
  }
}
```

Why does the compaction algorithm care about how I aliased `@value` when trying to compact the language maps? Shouldn't it still go back to the original simple language map?

**Comment by lanthaler** [comment]
It should not, the result should be the same. If it isn't, it is a bug in the JSON-LD processor you are using and should file a bug for it.

You can verify it with, e.g., my processor at http://www.markus-lanthaler.com/jsonld/playground/

**Comment by neothemachine** [comment]
Interesting, thanks! It happens on the official json-ld playground at http://json-ld.org/playground/

**Comment by msporny** [comment]
@neothemachine you'll want to file a bug against https://github.com/digitalbazaar/jsonld.js. That's what we use for the JSON-LD Playground.
