### ISSUE TITLE
Some examples of "Playground" get a "Processing error"

### ISSUE THREAD

**Issue by yaquawa** [json-ld/json-ld.org#422]
When I click the "Person" tab of "Playground" error occurred.

Processing error:

``` json
{
  "name": "jsonld.InvalidUrl",
  "message": "Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.",
  "details": {
    "code": "loading remote context failed",
    "url": "http://schema.org/",
    "cause": {
      "name": "jsonld.LoadDocumentError",
      "message": "URL could not be dereferenced, an error occurred.",
      "details": {
        "code": "loading document failed",
        "url": "http://schema.org/",
        "cause": {}
      }
    }
  }
}
```

**Comment by gkellogg** [comment]
Looks like a temporary error at schema.org is causing the load to fail. They must have made a recent configuration change to break this.

Gregg Kellogg

**Comment by danbri** [comment]
Hmm I thought we made a fix a couple weeks ago for this. 

https://github.com/schemaorg/schemaorg/pull/1221

/cc @RichardWallis

**Comment by msporny** [comment]
@yaquawa try it again, I'm not seeing the error.

We may want to put in a fallback for highly used cached contexts if the initial retrieval fails (with a warning, of course).

**Comment by danbri** [comment]
@msporny it was a sporadic error, caused by use of same URL for schema.org HTML homepage vs its content negotiable JSON-LD context variant (links above have more detail).

We've just deployed a fix to our testing site which can be found at webschemas.org - any feedback on that (and its HTTP header-related behaviour etc.) would be gratefully received. Generally webschemas.org just serves the "next release draft" from Github, currently the sdo-makemake branch.

**Comment by danbri** [comment]
Specifically it relates to whether the browser window being used has visited http://schema.org/ and gotten HTML first time around.

**Comment by yaquawa** [comment]
I'm not seeing the error now. Seems like Bug fixed?

**Comment by yaquawa** [comment]
@msporny

I'v tried again. No error message this time, but the `Compacted` format won't work?

**Comment by yaquawa** [comment]
@danbri 
Thanks!
Again, comes up a "Processing error" in Chrome. But both Safari and Firefox works fine. 
Strange.. Only Chrome won't work even in the incognito mode.

**Comment by danbri** [comment]
@yaquawa if you replace every use of 'schema.org' with 'webschemas.org', including visiting the homepage http://webschemas.org/ do you get the same behaviour (in Chrome at least)? /cc @RichardWallis

**Comment by yaquawa** [comment]
@danbri
Yes! With replacing the context to `http://webschemas.org/ `, everything works just fine(in Chrome of course).

**Comment by danbri** [comment]
Thanks, @yaquawa - that is encouraging. We aim to launch schema.org v3.1 soon, i.e. publish the site you see on webschemas.org to the official/main schema.org site. Perhaps we can check back here afterwards to confirm that the fix has worked? 

(for boring/scalability reasons the two sites, although on google appengine, are served with slightly different configurations)

**Comment by gkellogg** [comment]
Probably not related to #727, but works now in any case.

**Comment by thilop** [comment]
I think it has to be TLS: https://schema.org and not http://schema.org !

**Comment by davidlehn** [comment]
@thilop Both http://schema.org/ and https://schema.org/ should work in the playground.  There is a special [hack](https://github.com/json-ld/json-ld.org/blob/main/playground/playground.js#L1499) in the playground to rewrite schema.org when fetching the context.
