### ISSUE TITLE
Base URI per property [Duplicate]

### ISSUE THREAD

**Issue by JervenBolleman** [json-ld/json-ld.org#428]
This is an usecase that comes from the UniProt RDF to JSON translation. The UniProt datamodel is big and uses a lot of properties, not only that they have large number of URI namespaces.

e.g. in this example

```json
{
  "@context": {
    "@base": "http://purl.uniprot.org/uniprot/",
    "id": "@id",
    "a": "@type",
    "name": "http://purl.uniprot.org/core/name",
    "taxon": "http://purl.uniprot.org/taxonomy/",
    "organism": {
      "@id": "http://purl.uniprot.org/core/organism"
    }
  },
  "id": "P12345",
  "organism": {
    "id": "taxon:9606",
    "name": "Human"
  }
}
```

We would like to get rid of this prefixed taxon:9606 uri. i.e. in other words just show the 9606.

The main UniProt identifiers are dealt with by having set the base.

But for some specific properties I know that I will only have ids with a
certain prefix. This can't be specified in the context today.

e.g. I would like to have something like this.
```json
{
 "@context": {
   "@base": "http://purl.uniprot.org/uniprot/",
   "id": "@id",
   "a": "@type",
   "name": "http://purl.uniprot.org/core/name",
   "taxon": "http://purl.uniprot.org/taxonomy/",
   "organism": {
     "@id": "http://purl.uniprot.org/core/organism",
     "@MORE JSON-LD MAGIC" : "taxon"
   }
 },
 "id": "P12345",
 "organism": {
   "id": "9606",
   "name": "Human"
 }
}
```
That should translate to this
```
taxon:9606 up:name "Human" .
<P12345> up:organism taxon:9606 .
```
instead of this

```
<9606> up:name "Human" .
<P12345> up:organism <9606> .
```
There are ways to work around this with many inline contexts with their own base, but that is fragile (can have only one context per object so if we had two of this kind of predicates it would not work, in the UniProt case this does happen.)

**Comment by lisp** [comment]
this looks like a clear demonstration of a good argument for nesting contexts as such, rather than requiring that they always appear in-line.

**Comment by gkellogg** [comment]
This would fall out of #426. It would look something like the following:

```json
{
 "@context": {
   "@base": "http://purl.uniprot.org/uniprot/",
   "id": "@id",
   "a": "@type",
   "name": "http://purl.uniprot.org/core/name",
   "taxon": "http://purl.uniprot.org/taxonomy/",
   "organism": {
     "@id": "http://purl.uniprot.org/core/organism",
    "@content": {
      "@context": {
       "@base": "http://purl.uniprot.org/taxonomy/"
      }
    }
   }
 },
 "id": "P12345",
 "organism": {
   "id": "9606",
   "name": "Human"
 }
}
```

**Comment by JervenBolleman** [comment]
@gkellogg that looks exactly like what I want. Should I close this issue as it then duplicates #426 ?

**Comment by gkellogg** [comment]
Yes, you can close it. There will be a marker to this issue, as this references #426.

Once we achieve consensus on going forward with changes for 1.1, we can get spec text integrated into a draft; that should happen reasonably soon.

**Comment by newgene** [comment]
@gkellogg @JervenBolleman is the json-ld example in [this above comment](#issuecomment-250765924) is now supposed to work with 1.1 client (e.g. ruby one)? I tested it in [my 1.1 playground](http://jsonld.biothings.io/), it does not seem able to pick up the ```@base``` under "organism".

**Comment by gkellogg** [comment]
No, we never proceeded on having term `@content`, only term-specific `@context`. That would be more like the following:

```json
{
 "@context": {
  "@version": 1.1,
   "@base": "http://purl.uniprot.org/uniprot/",
   "id": "@id",
   "a": "@type",
   "name": "http://purl.uniprot.org/core/name",
   "taxon": "http://purl.uniprot.org/taxonomy/",
   "organism": {
     "@id": "http://purl.uniprot.org/core/organism",
    "@context": {
     "@base": "http://purl.uniprot.org/taxonomy/"
    }
   }
 },
 "id": "P12345",
 "organism": {
   "id": "9606",
   "name": "Human"
 }
}
```

It does not compact they way you expect (to be investigated), but it does expand using the embedded context.

**Comment by newgene** [comment]
@gkellogg got it, "scoped context" should be the solution here. And looks like might be a bug in the ruby client for processing the scoped context.
