### ISSUE TITLE
Add signing with bitcoin keys to playground

### ISSUE THREAD

**Issue by harlantwood** [json-ld/json-ld.org#431]
Now that https://github.com/digitalbazaar/jsonld-signatures/pull/9 is merged, I'll be submitting a PR shortly to sign JSON-LD with Bitcoin keys.  

Planned interface: change the "Signed" tab to "Signed with RSA Key" and add a new tab: "Signed with ~~Bitcoin~~ sha256-ecdsa-secp256k1-2016"

The new tab will have functionality similar to the Signed tab in this fork: http://peaceful-inlet-31266.herokuapp.com/playground/

cc @aquabu @ChristopherA @msporny

**Comment by BigBlueHat** [comment]
Did #442 close this? or is more pending?

**Comment by harlantwood** [comment]
Yes, thanks, closing.
