### ISSUE TITLE
Streaming Profiles for JSON-LD to/from RDF

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#434]
There have been some discussions on what it would take to be able to do a streaming parse of JSON-LD into Quads, and similarly to generate compliant JSON-LD from a stream of quads. Describing these as some kind of a profile would be useful for implementations that expect to work in a streaming environment, when it's not feasible to work on an entire document basis.

As currently stated, the JSON-LD to RDF algorithm requires expanding the document and creating a node map. A profile of JSON-LD which used a flattened array of node objects, where each node object could be independently expanded and no flattening is required could facilitate deserializing an arbitrarily long JSON-LD source to Quads. (Some simplifying restrictions on shared lists may be necessary). Outer document is an object, containing `@context` and `@graph` only; obviously, this only will work for systems that can access key/values in order, and for systems that ensure that `@context` comes lexically before `@graph` in the output. Obviously, only implementations that can read and write JSON objects with key ordering intact will be able to take advantage of such streaming capability.

Fo serializing RDF to JSON-LD, expectations on the grouping of quads with the same graph name and subject are necessary to reduce serialization cost, and marshaling components of RDF Lists is likely not feasible. Even if graph name/subject grouping is not maintained in the input, the resulting output will still represent a valid JSON-LD document, although it may require flattening for further processing. (Many triple stores will, in fact, generate statements/quads properly grouped, so this is likely not an issue in real world applications).

**Comment by danbri** [comment]
Perhaps the @context should be inline only, not by reference, ... (at least if the referenced document isn't understood to be frozen forever)?

**Comment by gkellogg** [comment]
That may be an orthogonal issue, as I don't see that that is actually required for streaming, but maybe an update to the security section.

For example, replicating all of the schema.org context would probably not be reasonable, and it can (should) be safely cached.

Perhaps there is a security profile, or an IoT profile that describes the needs for using inline, or upwardly invariant external contexts. This should be a separate issue.

Streaming profiles, in and of themselves, may not be required for IoT. The primary motivation was for dealing with large datasets and streaming sources/syncs.

**Comment by lisp** [comment]
> On 2016-10-23, at 22:45, Gregg Kellogg <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> ...
> 
> ... (Many triple stores will, in fact, generate statements/quads properly grouped, so this is likely not an issue in real world applications).
> 
where the json-ld encoding is the end-stage of a sparql query process, this is certainly the case.
as the client has complete control in the query context, any subsequent ordering requirements are redundant, if not counter-productive.





---
james anderson | james@dydra.com | http://dydra.com

**Comment by gkellogg** [comment]
Transfered to the WG: https://github.com/w3c/json-ld-api/issues/5.
