### ISSUE TITLE
compress brand images

### ISSUE THREAD

**Issue by Showcase-Joz** [json-ld/json-ld.org#439]
please consider compressing the brand assets for users own sites.

![compress images](http://www.clipular.com/c/4899629621837824.png?k=7eVfLve8dAY2IE3-GnBex5Tx0Qk)

**Comment by davidlehn** [comment]
What compression tool would you recommend?  The images were generated directly with inkscape:
https://github.com/json-ld/json-ld.org/blob/master/images/Makefile

**Comment by Showcase-Joz** [comment]
Just put the export images through http://compressor.io/compress individually 

Though could I suggest a possible guide for output too.

**Comment by veyndan** [comment]
@gkellogg Can this be closed now, considering #515 fixed this?
