### ISSUE TITLE
Add flag to disable compaction of relative URLs

### ISSUE THREAD

**Issue by davidlehn** [json-ld/json-ld.org#468]
When running any operation that includes compaction on a URL input, `@base` will be set to the URL. This will cause the output to convert any absolute URLs that are relative to `@base` to relative URLs, which can be undesirable in some applications.

Simply setting `base: null` in the options for these operations is an insufficient fix as these operations involve both an expansion phase and a compaction phase -- and this `null` `@base` will be applied during both phases when it is only desirable to apply it to the compaction phase. The only current workaround is to run expansion first, then run the desired operation on the expanded output (which will, unfortunately, needlessly run expansion again). Note: Perhaps the jsonld.js `skipExpansion` option can help mitigate this for simple compaction, but not for other operations.

Therefore, a flag is needed that prevents compaction to relative URLs for all operations that may include compaction (e.g. compaction, framing, flattening).

Historical discussion on this feature: https://github.com/json-ld/json-ld.org/issues/204
Related jsonld.js issue: https://github.com/digitalbazaar/jsonld.js/issues/171

**Comment by dlongley** [comment]
It could be argued that the default behavior should be to *not* compact to relative URLs (that the original decision was the reverse of what we should have made) and the flag would be to turn on compacting to relative URLs. If we're looking for the least disruptive fix, though, it would be to add a flag to prevent compaction from converting absolute URLs into relative URLs using `@base`.

**Comment by gkellogg** [comment]
If expansion leaves relative URLs, for one thing, it is not valid RDF. But it is certainly possible to do with Turtle if you specifically remove a document base.

When compacting, what logic actually comes into play here? If compacting with a base, the relative URLs certainly can be compacted against this, as they're not relatable to some absolute base. It would only be if compacting without an absolute base. I can certainly see that an expanded document containing relative URLs (in document-relative positions like `@id`) should not be compacted with or without a base; I'm not sure how they can be anyway, unless first made absolute.

As compaction is an optional step after flattening and framing, it seems we don't need to specify anything separate for those algorithms, only allow the flags to pass through.

Are there existing test cases which would be invalidated by this? Do you have any proposed algorithm changes?

**Comment by dlongley** [comment]
> When compacting, what logic actually comes into play here? If compacting with a base, the relative URLs certainly can be compacted against this, as they're not relatable to some absolute base. It would only be if compacting without an absolute base.

Converting absolute URLs to relative URLs during compaction when `@base` is set in the `@context` doesn't seem unexpected. That problem is that when you pass a URL to the compaction API, then the `@base` option gets automatically set to that URL for the compaction phase. It makes sense to set it to that for the expansion phase -- but it's unexpected for it to be applied to the compacted output.

**Comment by dlongley** [comment]
> Are there existing test cases which would be invalidated by this? Do you have any proposed algorithm changes?

I haven't had time to answer either of these yet. At a high-level the changes probably involve how we set the default `@base` option when compacting. We'll need to use the input URL as a default during the expansion phase but then use the empty string during the compaction phase.

**Comment by gkellogg** [comment]
I believe there is a provision for setting base in the test manifest entry for options. Not sure anything does this with null right now.

**Comment by gkellogg** [comment]
According to the [Test Vocabulary documentation](http://json-ld.org/test-suite/vocab.html), there is provision for a `base` property (not in options):

> The base IRI to use when expanding or compacting the document. If set, this overrides the input document's IRI.

Range is `rdfs:Resource`, but using `null` hear would make sense. This directly corresponds to the `base` option on `JsonLdOptions`.

Looking at my own implementation of `compactIri` for step 7, I only relativize `iri` if there is, in fact, a _base IRI_. Step 7 of IRI Compaction could make this clear:

> If _vocab_ is `false` and the document's base IRI is not `null`, transform `iri` to a relative IRI using the document's base IRI.

**Comment by dlongley** [comment]
The problem is with how defaults for the base IRI are set. For this case:

```js
compacted = compact(url, {"@context": {}});
```

The `compact` call here has an expansion phase (runs the expansion algorithm) and a compaction phase (runs the compaction algorithm on the expanded result of the first phase). I think what most people would expect would be this behavior:

During the expansion phase:

1. Since no `base` option is passed into the API, use the default of `url`.

During the compaction phase:

1. Since no `base` option is passed into the API and no `@base` is set in `@context`, use the empty string (`''`).

The processors we've implemented at DB do the above for the expansion phase, but they keep the same `base` setting of `url` for the compaction phase. This is the root of the trouble and unexpected behavior. If we didn't specifically say what should be done here in the API spec and don't have an appropriate test for it, then I think we should treat this as unspecified/errata and instead do what I suggest above.

**Comment by lanthaler** [comment]
Dave, I'm not sure I fully understand what behavior you would like here. Could you please post a simple example the illustrates what currently happens and what you would like there to happen instead? Thanks

**Comment by dlongley** [comment]
Suppose there's a JSON-LD doc at `https://example.org/foo` and you want to get it and compact it to your context.

Here's the original doc:

```js
{
  "@context": {
    "term": "https://example.org/vocab#term"
  },
  "@id": "#id1",
  "term": "some text"
}
```

When I run this:

```js
newContext = {
  "@context": {
    "newTerm": "https://example.org/vocab#term"
  }
}
compacted = compact("https://example.org/foo", newContext)
```

The expected result is:

```js
{
  "@context": {
    "newTerm": "https://example.org/vocab#term"
  },
  "@id": "https://example.org/foo#id1",
  "newTerm": "some text"
}
```

But instead, the result is:

```js
{
  "@context": {
    "newTerm": "https://example.org/vocab#term"
  },
  "@id": "#id1",
  "newTerm": "some text"
}
```

If this were run instead:

```js
newContext = {
  "@context": {
    "newTerm": "https://example.org/vocab#term"
  }
}
expanded = expand("https://example.org/foo")
compacted = compact(expanded, newContext)
```

The desired result would be produced but I had to run the expansion algorithm internally twice. To avoid that, I could run this crazy looking hack:

```js
newContext = {
  "@context": {
    "newTerm": "https://example.org/vocab#term"
  }
}
compacted = compact("https://example.org/foo", newContext, {
  expandContext: {
    "@base": "https://example.org/foo"
  },
  base: null
});
```

Instead, I would like the expected result above with the simplest call. If I wanted my output to have relative URLs, then I would have specified that in the options or via `@base` in my `newContext`.

**Comment by dlongley** [comment]
It seems the current default behavior makes me have to work (in part) with the data using the original context -- when the whole reason I called `compact` was to convert the data to my own context. Therefore, this seems like unexpected behavior.
