### ISSUE TITLE
Convert JSON message with array at the top level to JSON-LD format

### ISSUE THREAD

**Issue by rAseri** [json-ld/json-ld.org#471]
I’m currently try to convert JSON messages from 3rd party APIs to JSON-LD
format and keep backward compatibility with clients that uses old JSON
structure. 

For example

**Source JSON message**
```json
{
  "response": {
    "count": 2,
    "items": [
      {
        "id": 638865,
        "first_name": "Emma",
        "last_name": "Stone"
      },
      {
        "id": 1053682,
        "first_name": "Emma",
        "last_name": "Watson"
      }
    ]
  }
}
```
**JSON-LD message**
```json
{
  "@context": "/api/contexts/Person",
  "@id": "/api/friends",
  "@type": "http://www.w3.org/ns/hydra/core#collection",
  "response": {
    "count": 2,
    "items": [
      {
        "@id": "/api/person/638865",
        "@type": "http://schema.org/Person",
        "id": 638865,
        "first_name": "Emma",
        "last_name": "Stone"
      },
      {
        "@id": "/api/person/1053682",
        "@type": "http://schema.org/Person",
        "id": 1053682,
        "first_name": "Emma",
        "last_name": "Watson"
      }
    ]
  }
}
```
As you can see, I just added top level @context and @id, @type to root node
and inner nodes. These changes will not harm existing clients
that uses old JSON messages and they can keep working as before. It’s
looks ok.

But 3rd party API also provide JSON objects with array at the top level. 
```json
[
    {
        "id": 638865,
        "first_name": "Emma",
        "last_name": "Stone"
      },
      {
        "id": 1053682,
        "first_name": "Emma",
        "last_name": "Watson"
      }
]
```
So, my question is: How can I convert source JSON message to JSON-LD format and keep source JSON message structure when **source JSON message has array at the top level** ? How could I define @id and @type of root node?

**Comment by gkellogg** [comment]
You can add `@context`, etc. inside of each enclosed object. In this case, there is no root node, so it would not make sense to give an `@type` or `@id` to the array, if there were, you would simply enclose the array as being the property value of some other object having `@id` and `@type`.

```json
[
    {
        "@context": "/api/contexts/Person",
        "@id": "/api/person/638865",
        "@type": "http://schema.org/Person",
        "id": 638865,
        "first_name": "Emma",
        "last_name": "Stone"
      },
      {
        "@context": "/api/contexts/Person",
        "@id": "/api/person/1053682",
        "@type": "http://schema.org/Person",
        "id": 1053682,
        "first_name": "Emma",
        "last_name": "Watson"
      }
]
```

**Comment by niklasl** [comment]
Alternatively, you can use the [HTTP Link Header mechanism](https://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld) to supply the context out-of-band. As the documentation says:

>  Doing so allows JSON to be unambiguously machine-readable without requiring developers to drastically change their documents and provides an upgrade path for existing infrastructure [...]

**Comment by rAseri** [comment]
Thanks for answers. I’ll try to clarify.

I’m develop client application that will be able work with data in JSON-LD format. So, I’m also create proxy service, that convert JSON messages from 3rd party APIs to JSON-LD format for client application. For the client work properly, it’s required `@id,` `@type` and `@context` information for the root node object. In case, when top-level node is JSON object, it's ok (my first example). But, as you noticed, in case when array is top-level of source JSON object there is no root node. I would wrap array with other JSON-LD object with `@id` and `@type`, but it will changed source message structure and break backward compatibility for clients that not support JSON-LD. 

Yes, for `@context` I can use HTTP Link Header, but `@id` and `@type` I should define exactly in JSON-LD message, and it's a problem.

**Comment by KMax** [comment]
@niklasl Can `@id` and `@type` also be defined through the HTTP Link Header mechanism? Or it's only allowed for the `@context`?

E.g:
* `Link: </api/contexts/main.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"`
* `Link: </api/friends>; rel="http://www.w3.org/ns/json-ld#id"`
* `Link: </api/contexts/PersonCollection>; rel="http://www.w3.org/ns/json-ld#type"`

As I understand the spec doesn't say that only `@context` could be defined with the HTTP Link Header.

**Comment by gkellogg** [comment]
@KMax defining `@id` and/or `@type` on an array doesn't make sense, as these are properties of entities, and a top-level array describes multiple entities. You'd need to wrap the array in another entity, for which the array is the value of a property, but as you noted, this would break your API.

If you need to stick to this representation, you could describe each object of the array as having a reverse-relationship to an entity that does have an `@id` and `@type`. This is something that might make sense for a collection, and the collection needs a wrapper that describes where it lives, and other properties of the collection. For example, some proposals for [Hydra Collections](https://www.w3.org/community…) do this. In this way, you could provide the `@context` through the link header. It might looks something like the following:

```
HTTP/1.1 200 OK
...
Content-Type: application/json
Link: <http://example.com/api/contexts/Person>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"

[
    {
        "id": 638865,
        "first_name": "Emma",
        "last_name": "Stone",
        "member_of": {
          "@id": "http://example.com/api/people?page=1",
          "@type": "Collection",
          "manages": {
            "property": "schema:knows",
            "subject": "/alice"
          }
        }
      },
      {
        "id": 1053682,
        "first_name": "Emma",
        "last_name": "Watson",
        "member_of": "http://example.com/api/people?page=1"
      }
]
```

With the context defining something like the following:

```
{"@context": {.... "member_of": {"@reverse": "hydra:member"}}}
```
