### ISSUE TITLE
Playground does not provide JSON-LD 1.1

### ISSUE THREAD

**Issue by mitar** [json-ld/json-ld.org#484]
It would be great if one could play with proposed 1.1 version. That would help to give feedback on it.

**Comment by gkellogg** [comment]
Indeed. Hopefully, at some point @dlongley will be able to work on updates. Alternatively, that someone else do a PR to jsonld.js with the proposed updates that he can accept.

**Comment by gkellogg** [comment]
It does now, old issue.
