### ISSUE TITLE
Bug in 1.1 Flatten Spec?

### ISSUE THREAD

**Issue by kal** [json-ld/json-ld.org#492]
In the Flatten algorithm, step 6.6.3 is written as:

Otherwise, append _element_ to the `@list` member of _list_.

However when this is implemented, the processor fails unit test flatten-0029 as the @list element ends up with empty objects. I believe that the correct wording for this step should be:

Otherwise, append _reference_ to the `@list` member of _list_.

This works, and passes the unit test, _reference_ having been initialized in step 6.6.1

Can you confirm if this is a bug in the spec (otherwise its a bug in my implementation somewhere! ;-)

**Comment by gkellogg** [comment]
That would be in the [Node Map Generation Algorithm](http://json-ld.org/spec/latest/json-ld-api/#algorithm-11).

And, yes, thanks, it should append _reference_ not _element_.
