### ISSUE TITLE
Bug in Serialize RDF as JSON-LD Algorithm

### ISSUE THREAD

**Issue by kal** [json-ld/json-ld.org#493]
In step 5.3.3, if the value of the @id member of node is not a blank node identifier the loop should terminate. The start of this step should therefore read something like:

> While property equals rdf:rest, **the value of the @id member of node is a blank node identifier,** 
> the array value of the member of node usages map associated with the @id member of node has only one member, 

(addition highlighted)

**Comment by gkellogg** [comment]
Step 5.3.3.5 terminates the loop after appending values to _array_ and updating _node_. However, I note that my implementation checks to see that _node_ is a blank node in the same place you suggest. This seems like a good change to me.

@dlongley @lanthaler?
