### ISSUE TITLE
Bug in setup of node usages map in Serialize RDF as JSON-LD Algorithm

### ISSUE THREAD

**Issue by kal** [json-ld/json-ld.org#494]
Step 4.5.8.2 currently reads:

> Append the value of the `@id` member of node to the object member of node usages map, unless it already exists.

However if you don't add duplicate `@id` values to the array, you fail to detect the case where a list node is referred to by multiple statements. I think that the step should probably read simply:

> Append the value of the `@id` member of node to the object member of node usages map.

**Comment by gkellogg** [comment]
This is, in fact, what my own processor does.
