### ISSUE TITLE
Bug on the playground?

### ISSUE THREAD

**Issue by stuchalk** [json-ld/json-ld.org#497]
On Saturday I was using context files fine on one of my github projects (http://stuchalk.github.io/scidata/) and now even the simplest example (http://tinyurl.com/lw7o4qd) throws a 'loading remote context failed' error.  I have looked through the list of possible reasons for the error and I don't see anything that is not working that I have control of.  Ideas?

Stuart

**Comment by davidlehn** [comment]
The site hosting moved from http to https and this caused some havoc.  When the playground is loaded from https the browser doesn't allow requests to http.  The JSON-LD processor needs to do that to fetch contexts.  We now have a simplistic proxy in place to help deal with the issue.  Please try again and verify it's working.

**Comment by stuchalk** [comment]
I can verify that its working fine now.  Thanks!
