### ISSUE TITLE
Unexpected behavior from framing: fail to embed, fail to default

### ISSUE THREAD

**Issue by cboettig** [json-ld/json-ld.org#499]
Consider data such as:

```json
{
  "@context": "http://schema.org",
  "@type": "SoftwareSourceCode",
  "author": 
    {
      "@type": "Person",
      "givenName": "Carl",
      "familyName": "Boettiger",
      "email": "cboettig@gmail.com",
      "@id": "http://orcid.org/0000-0002-1642-628X"
    },
  "maintainer": "http://orcid.org/0000-0002-1642-628X"

}

```

Under this frame: (e.g.  a frame designed to always extract a value for `author.familyName`, `author.affiliation` and `maintainer.familyName`, with defaults for the latter two)

```json
{"@context": "http://schema.org", 
 "@embed": "@always",
 "author": {
   "familyName": {},
   "affiliation": 
     {"@default": "@null"}
  },
 "maintainer": {
   "familyName": { "@default": "none" }
 }
}
```

The output has the following issues (or so it seems):

1. Maintainer is not embedded, nor does it get a default value (`maintainer.familyName` fails).  

2. Even without `@embed` set to always, this still give unpredictable behavior: I expect `@embed` to be `@last` by default, so that `maintainer.familyName` would work, but `maintainer` is listed last but still not embedded (we just get the id).  

3. Also surprising is that if I simply drop `familyName: {}` from the `author` above, I get no match, even though I have not set `@explicit` to true.    

Not sure where I've gone wrong.  (I do note that `author.affiliation` is getting set to `null` as expected).  

This example in the [playground](https://json-ld.org/playground/#startTab=tab-framed&copyContext=true&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%22%2C%22%40type%22%3A%22SoftwareSourceCode%22%2C%22author%22%3A%7B%22%40type%22%3A%22Person%22%2C%22givenName%22%3A%22Carl%22%2C%22familyName%22%3A%22Boettiger%22%2C%22email%22%3A%22cboettig%40gmail.com%22%2C%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-1642-628X%22%7D%2C%22maintainer%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-1642-628X%22%7D&frame=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%22%2C%22%40embed%22%3A%22%40always%22%2C%22author%22%3A%7B%22familyName%22%3A%7B%7D%2C%22affiliation%22%3A%7B%22%40default%22%3A%22%40null%22%7D%7D%2C%22maintainer%22%3A%7B%22familyName%22%3A%7B%22%40default%22%3A%22http%3A%2F%2Fme.org%22%7D%7D%7D)

**Comment by gkellogg** [comment]
@cboettig:

> Maintainer is not embedded, nor does it get a default value (maintainer.familyName fails).

The `maintainer` property is either not defined in the schema.org context, or is defined as something other than `@type: @id`. If you expand it, you'll see it come out as the following:

```json
"http://schema.org/maintainer": [
      {
        "@value": "http://orcid.org/0000-0002-1642-628X"
      }
    ]
```

Try using the following frame:

```json
{"@context": ["http://schema.org", {
    "maintainer": {"@type": "@id"}
  }],
 "@embed": "@always",
 "author": {
   "familyName": {},
   "affiliation": 
     {"@default": "@null"}
  },
 "maintainer": {
   "familyName": { "@default": "none" }
 }
}
```

See if that handles your problem. When facing issues like this, expanding in the playground is useful to see what's going on.

**Comment by cboettig** [comment]
@gkellogg silly me, thought I changed that out.  I still have the same problem though if I change `maintainer` to `creator` or `editor` or other `schema.org` term.  

I guess the real problem is that I haven't explicitly declared `@type` for `maintainer` (or for `editor`, if I was sticking with a schema-namespace)?  Declaring  `@id` is for the `maintainer` seems to allow the node to resolve just fine.  Still does not give me the behavior I expect though.  Despite my `@embed` @`always`, I'm not getting the author node?  The expanded version looks fine, must be an issue with my frame?

[New Playground example](https://json-ld.org/playground/#startTab=tab-expanded&copyContext=true&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%22%2C%22%40type%22%3A%22SoftwareSourceCode%22%2C%22author%22%3A%7B%22%40type%22%3A%22Person%22%2C%22givenName%22%3A%22Carl%22%2C%22familyName%22%3A%22Boettiger%22%2C%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-1642-628X%22%7D%2C%22creator%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-1642-628X%22%7D%7D&frame=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%22%2C%22%40embed%22%3A%22%40always%22%2C%22author%22%3A%7B%22familyName%22%3A%7B%7D%2C%22affiliation%22%3A%7B%22%40default%22%3A%22%40null%22%7D%7D%2C%22creator%22%3A%7B%22familyName%22%3A%7B%22%40default%22%3A%22SurName%22%7D%2C%22affiliation%22%3A%7B%22%40default%22%3A%22%40null%22%7D%7D%7D)

**Comment by gkellogg** [comment]
> I still have the same problem though if I change maintainer to creator or editor or other schema.org term.

The problem could be that schema.org does not assume that values of `maintainer`, `editor`, etc. will be objects, so when used as a simple string in the input document will not be treated as objects. You either must override the term definitions, as I did, or use the expanded form in your input. You shouldn't need to declare a `@type`, but if you create an object value, adding an `@type` is generally a good idea IMHO.

I think the `@embed: @always` should cause both `author` and `maintainer` to be in expanded form. Perhaps @dlongley can explain this behavior.
