### ISSUE TITLE
Understanding when @type and @id are compacted to type and id

### ISSUE THREAD

**Issue by cboettig** [json-ld/json-ld.org#500]
When compacting the following
```
{
  "@context": {
    "schema": "http://schema.org/",
    "author": "schema:author",
    "givenName": "schema:givenName"
  },
  "@type": "SoftwareSourceCode",
  "author": {
    "@id": "http://example.com/bob",
    "givenName": "Bob"
  }
}
```

the properties `@type` and `@id` are left with the `@` signs in place.  However, if we use `http://schema.org/` as the URI for the context, or append it in an array for the context, then compacting removes the `@` on types.  My impression is that this means my context above is somehow incomplete, but I'm not really sure how or why.

Is it possible to amend my context above so that compaction will remove the `@` for `type` and `id`, without pulling in all of `schema.org` as a valid context?

**Comment by gkellogg** [comment]
Your context is complete, given the document you have. If you used `"@context": "http://schema.org/"`, then you would pick up all of the terms defined in the schema.org context, which includes aliases for `@id` and `@type`.

**Comment by cboettig** [comment]
Right, but it seems I'm not permitted to alias `@id` and `@type` myself since the are protected terms?  But `schema.org` is allowed to alias them?

**Comment by cboettig** [comment]
nevermind, I'm an idiot.  I was trying to do `"@id": "id"` instead of the other way around. whoops.
