### ISSUE TITLE
Handling properties as @container as @list and @type as @id

### ISSUE THREAD

**Issue by dankawka** [json-ld/json-ld.org#508]
Hello, while playing in playground I found a bug... probably. The problem happens when we declare field as `
"@container": "@list",
"@type": "@id"
`

You can see example here: 
[link](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22name%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22https%3A%2F%2Fschema.org%2Fname%22%7D%7D%2C%22name%22%3A%5B%5D%7D&context=%7B%22%40context%22%3A%7B%22name%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22https%3A%2F%2Fschema.org%2Fname%22%7D%7D%7D)

When you provide empty array the compaction fails and we get full URI instead of `abc`. If we provide at least 1 value, the compaction works fine and we get `abc` property as array with provided values which is expected.

Expected result after compaction empty array would be empty array, rather than expanded form.

**Comment by davidlehn** [comment]
Note the context doc should be of the form `{"@context":{ ...}}` vs just top level aliases.  Though most libs will work either way.  The playground uses jsonld.js and it looks like it's a bug with that code.  The example works with http://www.markus-lanthaler.com/jsonld/playground/.  A test similar to the above example should be added to the json-ld.org test suite and an issue filed at https://github.com/digitalbazaar/jsonld.js/issues to fix it.

**Comment by dankawka** [comment]
You are right, it works for me too on Markus Lanthaler's version. I added PR with test for that: https://github.com/json-ld/json-ld.org/pull/509, also will create issue on jsonld.js repo.

**Comment by gkellogg** [comment]
A strict reading of the [Term Selection Algorithm](https://json-ld.org/spec/latest/json-ld-api/#algorithm-8) shows why jsonld.js (and Ruby JSON-LD) do note compact this as you might expect.

Basically, for the term to be selected, there needs to be at least one item in the list that matches the type/language expectations. This will likely require an update to the algorithm description in 1.1 to clarify this.

cc/ @lanthaler @niklasl @msporny

**Comment by gkellogg** [comment]
Alternatively, if some simple text will do to update the algorithm, we could add it as 1.0 errata.
