### ISSUE TITLE
playground: remote documents / contexts permalink handling broken

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#513]
__Steps to reproduce:__
1. Go to the [playground](https://json-ld.org/playground/)
2. Put `https://linked.art/example/object/11.json` into the document text entry
3. Click the document icon. Everything good so far.
4. Click the permalink button (generating [this](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=https%3A%2F%2Flinked.art%2Fexample%2Fobject%2F11.json))
5. Copy the link and open in new browser tab. 

__Expected Behavior:__

The permalink should recreate the experience of the first steps. Instead the javascript errors as `url` is null, not the string expected at line 1339.

This is a change in behavior over the last few months, as this used to work as expected (and we generate the "permalinks" [sic?] in our documentation)

**Comment by gkellogg** [comment]
The playground needs a champion.

**Comment by dlongley** [comment]
And I think we should remove the permalink function because the `gist` function does the same thing and does it *much* better.

**Comment by azaroth42** [comment]
For remote documents, having at least an "API" (in the very loosest sense) for how to construct links such that the documents are displayed in the playground is __extremely__ useful. That doesn't need to be called a permalink, but it's not handled by gists.

**Comment by azaroth42** [comment]
The bug in this case is that from here:
  https://github.com/json-ld/json-ld.org/blob/master/playground/playground.js#L142

The `toggleRemote()` function is called before setting the remoteURL. `toggleRemote()` then calls `fetchRemote()`, which looks for the unset url here:
  https://github.com/json-ld/json-ld.org/blob/master/playground/playground.js#L588

`setRemoteUrl()` also calls `fetchRemote()`

Not to question the design choice too much but it seems like a minor refactor to pull the fetchRemote() calls up rather than having them as (dangerous, it turns out) side effects of setting and toggling would be a relatively easy fix?

**Comment by azaroth42** [comment]
Turns out flipping the order of 142/143 fixes at least the symptoms.

**Comment by azaroth42** [comment]
Thanks! 

https://json-ld.org/playground/#startTab=tab-expanded&json-ld=https://linked.art/example/object/11.json  is now working as expected :)
