### ISSUE TITLE
Expired TLS certificate for non-SNI connections

### ISSUE THREAD

**Issue by ansell** [json-ld/json-ld.org#519]
The server hosting ``json-ld.org`` is showing an expired certificate to users who connect without TLS SNI. See the report from ssllabs that concludes that "This site works only in browsers with SNI support":

https://www.ssllabs.com/ssltest/analyze.html?d=json-ld.org

Is it possible to update the default (non-SNI) certificate to allow these users to connect?

**Comment by ansell** [comment]
Based on the expired certificate's name "TRAEFIK DEFAULT CERT", it may be related to this feature request: https://github.com/containous/traefik/issues/1814

**Comment by davidlehn** [comment]
json-ld.org is running behind traefik using a let's encrypt cert.  That front end is for a number of other hosts too so it wouldn't really work to just pick one host as a default.  What tools are you using that don't support SNI?  (It's kind of unclear from that referenced issue)

**Comment by ansell** [comment]
That is sound reasoning to me 👍. I am not sure what version of java they are using yet, but I thought all recent (for a few years) java versions supported SNI. Closing this as won't fix based on the operational requirements for json-ld.org.
