### ISSUE TITLE
Should we support lists of lists?

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#52]
Currently we do not support lists of lists since Gregg got into some problems in trying to make them work algorithmically and didn't have a real use case.

We should discuss whether we would like to support that or not and what happens if someone uses that feature nevertheless.

**Comment by alpha-beta-soup** [comment]
There's a use case for lists of lists in GeoJSON-LD: https://github.com/geojson/geojson-ld/issues/12 (all non-point, non-empty geometries cannot be represented).

**Comment by gkellogg** [comment]
Lists of lists are supported in the working group draft: https://w3.org/TR/JSON-LD11.

The community group, which this site is based on, handed off work to the working group some time ago. 

There is a specific example for Geo-JSON in the spec.
