### ISSUE TITLE
Scope context by @type: mapped term or rdf uri?

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#521]
In the description of [scoped contexts by @type](https://json-ld.org/spec/latest/json-ld/#scoped-contexts), it says:

> Scoping can also be performed using a term used as a value of @type:

I believe that this is the term used for for the type's URI, not the type's URI directly? Thus if there were two separate terms, both mapped to the same type URI, they could each have different scoped mappings for the same terms and predicates.

For example:

```
{
  "AnnotationCollection": {
    "@id": "as:Collection",
    "@context": {
      "label": {
        "@id": "rdfs:label",
        "@container": ["@language", "@set"]
      }
    }
  },
  "Collection": {
    "@id": "as:Collection"
  },
  "label": "rdfs:label"
}  
```

This would allow the `Collection` to have `label` as a string, and `AnnotationCollection` to have `label` as a language map requiring an array of values for each language.

Correct?  And if so, does this need clarification in the spec?

**Comment by gkellogg** [comment]
It is the term having an `@context` in its term definition which is used as the value of `@type` which enables this behavior, it really isn't related to the URI the term expands to. You're correct in your interpretation.

We could perhaps make this more explicit in that sentence, but IMO, it's clear as is. However, the fact that you found it confusing should be enough to try for an improvement. Do you have an alternative wording you can suggest?
