### ISSUE TITLE
Missing definition of `label` in example 18

### ISSUE THREAD

**Issue by zimeon** [json-ld/json-ld.org#522]
Assuming the intent is to mirror example 17 with a complete example including `@base`, I think example 18 in https://json-ld.org/spec/latest/json-ld/#base-iri should have `"label": "http://www.w3.org/2000/01/rdf-schema#label"` in the context.

**Comment by zimeon** [comment]
@gkellogg - did you intend to drop the indentation within `@context`?

**Comment by gkellogg** [comment]
@zimeon no, thanks, it was inadvertent.
