### ISSUE TITLE
Support bitcoin testnet keys 

### ISSUE THREAD

**Issue by harlantwood** [json-ld/json-ld.org#523]
https://github.com/w3c-vc/playground/issues/3 was created in the wrong repo, should be here.  Copy pasting that and other related info here:

@ChristopherA said:

> For the DID:BTCR hackathon next week, we will be using testnet keys rather than real bitcoin keys. Testnet private keys begin with m, whereas mainnet keys begin with 1. Otherwise the crypto is the same. This playground should support both.
>
> As we will be creating test verifiable claims next week (July 10th) for the hackathon, and this should be an easy fix, can someone prioritize supporting testnet keys ASAP, or let us know if it is not possible? Thanks!

More from @ChristopherA: 

> ...the value under creator, currently specified as 
> 
>     “creator": "ecdsa-koblitz-pubkey:1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER",
> 
> Is in fact not a public key, but base58-check hash of the public key.
> 
> The private key for our demo is also a base58check encoded value of the full private key: L4mEi7eEdTNNFQEWaa7JhUKAbtHdVvByGAqvpJKC53mfiqunjBjw
> 
> However, there is no standard base58-check for public keys (a prefix such that the value starts with 4 was proposed but never implemented), but there are tools you can see that the compressed public key (we don’t used uncompressed anymore) for that private in hex 020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b and the base58check is 1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER
> 
> Thus to correct, this means that the default example should look like:
> 
>     “creator": "ecdsa-koblitz-pubkey:020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b",
> 
> or possibly:
> 
>     “creator”: “ecdsa-koblitz-pubkey-hex:020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b”,

**Comment by azaroth42** [comment]
A meta-issue (per #524) is the extent to which the playground should support features beyond the JSON-LD specifications, rather than having separate playgrounds for extensions and overlays such as this.  I would prefer separate playgrounds, rather than putting everything into the current site, to try and keep the codebase manageable.

**Comment by harlantwood** [comment]
@azaroth42 I don't disagree.  My latest comment on the sitch here: https://github.com/json-ld/json-ld.org/pull/524#issuecomment-358150855 .
