### ISSUE TITLE
Bug in the framing algorithm spec?

### ISSUE THREAD

**Issue by eroux** [json-ld/json-ld.org#531]
When reading the [framing algorithm](https://json-ld.org/spec/latest/json-ld-framing/#framing-algorithm) my feeling is that point 5.1 and 5.2 are bogus in this order. Currently we can read:

```
5.1 Initialize output to a new dictionary with @id and id and add output to link associated with id.

5.2 If embed is @link and id is in link, node already exists in results. Add the associated node object from link to parent and do not perform additional processing for this node.
```

which I interpret as the following JS code:

```javascript
link = {...};
id = ...;
// 5.1
output = {id: id};
link.id = output;
// 5.2
if (embed == "@link" && typeof link.id !== "undefined") {
    addAssociatedNodeFromLinkToParent();
    continue;
}
```

which has a problem in the second condition of the if: in `5.1` we already added `id` to `link`, so `id is in link` is always true... or is there something I didn't read properly?

**Comment by gkellogg** [comment]
> 5.1 Initialize output to a new dictionary with @id and id and add output to link associated with id.

The "with __@id__ and _id_" is intended to mean "with the key __@id__ referencing _id_". I believe this language is used elsewhere, but we can certainly update to something more accurate and comb for other uses.

My code implementing it is [here](https://github.com/ruby-rdf/json-ld/blob/develop/lib/json/ld/frame.rb#L57-L63), although the order is reversed, which shouldn't really matter. The fact that it says "do not perform additional processing for this node" would make the initialization of `output` a no-op, but I don't have a problem with reversing it.

**Comment by eroux** [comment]
Well, I disagree, if you reverse your code to something in line with the spec:

```ruby
        // 5.1
        output = {'@id' => id}
        link[id] = output

        // 5.2
        if flags[:embed] == '@link' && link.has_key?(id)
          # add existing linked subject
          add_frame_output(parent, property, link[id])
          next
        end
```

the result will be different, as `ink.has_key?(id)` will always be true.

**Comment by gkellogg** [comment]
Note that the consensus on #140 is to remove support for `@link`, at least in the specification, so this would also obviate any need for this PR.

Propose to close when updating framing to remove spec language (due to it's nature, there never were any conformance tests).

**Comment by eroux** [comment]
closing, thanks!
