### ISSUE TITLE
bug in frame expansion algorithm?

### ISSUE THREAD

**Issue by eroux** [json-ld/json-ld.org#532]
I have a frame that just specifies an id:

```json
{
  "@id": "http://purl.bdrc.io/resource/W30020"
}
```

as I just want this ID to be framed. It sounds quite legit to me, but when [expanding the frame](https://json-ld.org/spec/latest/json-ld-api/#expansion-algorithms), the result of the expansion is null because of `13.2`. Maybe this could be true only if `frame expansion` flag is not present?

**Comment by eroux** [comment]
In fact, the spec (if I interpret it correctly) here is in contradiction with the [Framing Test](https://json-ld.org/test-suite/) `Test 0022: Match on @id` which has

input:
```json
{
  "@context": {"ex": "http://example.org/"},
  "@graph": [{
    "@id": "ex:Sub1",
    "@type": "ex:Type1"
  }, {
    "@id": "ex:Sub2",
    "@type": "ex:Type2"
  }]
}
```
frame:
```json
{
  "@context": {"ex": "http://example.org/"},
  "@id": "ex:Sub1"
}
```

output:

```json
{
  "@context": {"ex": "http://example.org/"},
  "@graph": [{
    "@id": "ex:Sub1",
    "@type": "ex:Type1"
  }]
}
```

Here the frame should expand to null according to the spec, while in this test it clearly isn't the case.

**Comment by eroux** [comment]
Note that the test is bogus anyway: with the latest [frame matching algorithm](https://json-ld.org/spec/latest/json-ld-framing/#frame-matching) I cannot find any reason why `ex:Type2` wouldn't match.

**Comment by dlongley** [comment]
Yes, I think it's a bug to expand the frame to null when there are no properties other than `@id` when the `frame expansion` flag is set.

Regarding why `ex:Type2` won't match -- it's because the frame has an `@id` and the `@id` for the node that has an `@type` of `ex:Type2` does not have a matching `@id`.

The framing algorithm text should be more clear that when the frame has an `@id`, it is used exclusively to match, i.e. if a node doesn't have that `@id`, it will not match.

**Comment by eroux** [comment]
Ok, then indeed the text should be completed/amended. Thank you!

**Comment by gkellogg** [comment]
Yes, there's a missing clause in 13.2 which should allow an object with just `@id` when framing.

> Note that the test is bogus anyway: with the latest frame matching algorithm I cannot find any reason why ex:Type2 wouldn't match.

No, this is a specific feature in 1.1 to match on `@id`. See step 1 in [Frame Matching](https://json-ld.org/spec/latest/json-ld-framing/#frame-matching):

> Node matches if it has an `@id` property including any _IRI_ or _blank node_ in the `@id` property in _frame_.

My code is [here](https://github.com/ruby-rdf/json-ld/blob/develop/lib/json/ld/frame.rb#L291-L296).

**Comment by eroux** [comment]
I've read the Frame matching, and I understand the intent, but the wording is not precise enough because it doesn't say that if the frame contains `@id`s, then nodes that don't match one of the values should not match. It only says that nodes that have these `@id`s match. So my initial reaction was not to decide at this point and to go to point `2`, but it's not the intended behavior. So I think a wording like

> If the frame contains at least one @id property, then the node matches if it has an @id property matching any IRI or blank node in the @id property of the frame, and the node does not match if it has no such property.

To express that in JavaScript-ish, the current wording says:

```
// 1.
if (node.id in frame.ids)
    return true;
// 2.
etc.
```

while the intent is

```
// 1.
if (frame.ids)
    return node.id in frame.ids;
// 2.
etc.
```

**Comment by gkellogg** [comment]
Yes, that's a good point. If the frame has an `@id` to use for matching, and a given object has an `@id` that does not match, any attempt to match __must__ be aborted. I'll tag this for update.

**Comment by gkellogg** [comment]
@eroux There is a missing clause in the Expansion Algorithm 13.2. I'm amending as follows:

> Otherwise, if _result_ is a dictionary whose only key is `@id`, set result to `null`. When the `frame expansion` flag is set, a dictionary containing only the `@id` key is retained.

This style  matches that used elsewhere in the algorithm. Alternatively, it could be something like the following:

> Otherwise, if _result_ is a dictionary whose only key is `@id`, and the `frame expansion` flag is not set, set result to `null`.

Regarding node matching in the framing algorithm, how about amending the first step as follows:

> _Node_ matches if it has an `@id` property including any IRI or blank node in the `@id` property in _frame_. Otherwise, if _frame_ has a non-empty `@id` property  which is not an empty dictionary, _node_ does not match.

The Ruby code for this is the following:

```ruby
return ids.include?(subject['@id']) if !ids.empty? && ids != [{}]
```
