### ISSUE TITLE
why are lang tag lower-cased?

### ISSUE THREAD

**Issue by eroux** [json-ld/json-ld.org#533]
The [expansion algorithm](https://json-ld.org/spec/latest/json-ld-api/#expansion-algorithm) `8.4.7` reads:

```
If expanded property is @language and value is not a string, [...]. Otherwise, set expanded value to lowercased value.
```

Is there a reason why the value is lower-cased? 

This introduces some annoyances because RDF 1.1 [states](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) that 2 literal terms are equals IIF their value and language tags are equal character by character, so in a case sensitive way. My experience is the following:

- have some RDF triples containing a literal `"whatever"@bo-Latn` (the canonical BCP-47 form)
- convert to JSON-LD, to `{"@value": "whatever", "@language": "bo-latn"}` (lower case, as specified in the JSON-LD spec)
- convert back to RDF as `"whatever"@bo-latn` (lower-case)
- compare your two set of triples
- experience puzzlement and annoyance

I know, there are some workarounds like having all tags lower-cased in RDF or canonicalizing during JSON-LD -> RDF conversion, but really, does it have to be that complex?

See also [this issue](https://github.com/jsonld-java/jsonld-java/issues/199).

**Comment by gkellogg** [comment]
Lower casing basically follows [RDF11-Concepts](https://www.w3.org/TR/rdf11-concepts/):

> A literal is a `language-tagged string` if the third element is present. Lexical representations of language tags `may` be converted to lower case. The value space of language tags is always in lower case. The lexical forms may, in fact, differ; I don't know of any `sameTerm` like tests for RDF serializations, SPARQL or JSON-LD that specifically look to see if two language-tagged literals that different only the the case of the language compare; but this is likely due to implementors lobbying to _not_ force such a comparison due to the _may_ clause in Concepts.

JSON-LD follows this `may` language in expansion. I believe you'll find that many (most?) RDF/SPARQL implementations will found `"foo"@en"` and `"foo"@EN` to be the same term because of such internal normalization.

As to _why_ JSON-LD 1.0 does this, this requires looking through the issue list. There is some discussion in #174 and #181.

**Comment by eroux** [comment]
Well, here are a few thoughts about this. Let's discriminate between value equality and term equality. Two terms can be equal in terms of value but not in terms of term. For instance

```
"01"^^xsd:nonNegativeInteger
```

and

```
"+1"^^xsd:integer
```

are not term-equal but are value-equal. If you put them into Jena-Fuseki and fetch them, you will receive them both as `"1"^^xsd:integer`, as Jena-Fuseki only stores values, not terms. But JSON-LD does store terms, I can have

```json
"prop": {
    "@type": "xsd:nonNegativeInteger",
    "@value": "01"
}
```

and

```
"prop": {
    "@type": "xsd:integer",
    "@value": "+1"
}
```

same value, different terms. I can do that with JSON-LD. Except with language strings! When converting from RDF, JSON-LD only translates the value of the literal (`@en`) and not the term (`@EN`). It looks to me as something incoherent... As I see it it should either just store values, and allow only

```json
"prop": 1
```

(no `xsd:nonNegativeInteger`, etc.) which only belong to the term, or store the terms, including the case of the language tag. What do you think?

**Comment by gkellogg** [comment]
Does Fuseki match `"foo"@en` and `"foo"@EN` using _sameTerm_? I didn't think so, but could be remembering wrong.

In any case, there would need to be a pretty compelling case to change this behavior in 1.1. I'd certainly like to here form @msporny, @dlongley, @niklasl, and @lanthaler.

**Comment by eroux** [comment]
Fuseki doesn't store terms, it only stores values, so when you feed it with `"foo"@EN` and query the triple, it will return "foo@en". There's no notion of "using sameTerm" in Fuseki (AFAIU).

Well, I think that's a case I'm trying to make: JSON-LD does store terms, not values, except when it comes with language tags. If it was storing values, then for the sake of consistency, when it's fed with `"001"^^xsd:integer` it should output:

```json
{
    "@value": "1",
    "@type": "xsd:integer"
}
```

but it doesn't and keeps the padding 0. So the way I view it it stores terms for everything but lang tag. So why not just storing terms also for the lang tag?

**Comment by lisp** [comment]
good morning;

> On 2017-08-22, at 09:13, Elie Roux <notifications@github.com> wrote:
> 
> Fuseki doesn't store terms, it only stores values, so when you feed it with "foo"@EN and query the triple, it will return "foo@en". There's no notion of "using sameTerm" in Fuseki (AFAIU).
> 
> Well, I think that's a case I'm trying to make: JSON-LD does store terms, not values, except when it comes with language tags. If it was storing values, then for the sake of consistency, when it's fed with "001"^^xsd:integer it should output:
> 
> {
>     
> "@value": "1"
> ,
>     
> "@type": "xsd:integer"
> 
> }
> 
> but it doesn't and keeps the padding 0. So the way I view it it stores terms for everything but lang tag. So why not just storing terms also for the lang tag?

because the documents which describe how to work with language tags can be interpreted to say that it would not be good practice to retain the case and compare using the literals as such.
see https://tools.ietf.org/html/bcp47#section-2.1.1 and https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal .
the former stipulates that they are always to be treated as case insensitive and the latter permits canonicalization.
in order to follow the first without taking advantage of the latter, all algebra operations would require more complex comparisons.

best regards, from berlin,

**Comment by eroux** [comment]
Well, I agree that the handling of the case of language in RDF 1.1 is terrible, but that's what it is: two literals are not term equals if the case of their lang tags are not the same. That's what causes the problem here. 

My point is that I see no reason why literal terms should be modified by JSON-LD *only* in the case of lang tags. If JSON-LD wants to do some sort of normalization then fine, please make it an option and do an actual normalization removing padding 0s, etc. but make it consistent...

**Comment by lisp** [comment]
good morning;

> On 2017-08-22, at 09:53, Elie Roux <notifications@github.com> wrote:
> 
> Well, I agree that the handling of the case of language in RDF 1.1 is terrible, but that's what it is: two literals are not term equals if the case of their lang tags are not the same. That's what causes the problem here.
> 
> My point is that I see no reason why literal terms should be modified by JSON-LD only in the case of lang tags. If JSON-LD wants to do some sort of normalization then fine, please make it an option and do an actual normalization removing padding 0s, etc. but make it consistent…

the point is that, as the recommendations permit and “best practice” suggests, the lexical processing layer should canonicalize.
in which case, the internal term lexical expression is the same for any case formulation of a given language tag.
in which case they are the same term.

this is not the same as d-entailment for numeric values.

best regards, from berlin,

**Comment by eroux** [comment]
I'm sorry I think I got lost... 

> the point is that, as the recommendations permit and “best practice” suggests, the lexical processing layer should canonicalize.

Ok

> in which case, the internal term lexical expression is the same for any case formulation of a given language tag.

how do you defined "internal term lexical expression"? I'm not sure I'm following... What I see in the RDF spec you pointed is:

> Literal term equality: Two literals are term-equal (the same RDF literal) if and only if the two lexical forms, the two datatype IRIs, and the two language tags (if any) compare equal, character by character. Thus, two literals can have the same value without being the same RDF term. For example:
>
>      "1"^^xs:integer
>      "01"^^xs:integer
>    
> denote the same value, but are not the same literal RDF terms and are not term-equal because their lexical form differs.

So it's pretty clear that they are not the same term... they denote the same value, I agree, but I can't see why you would say they are the same term... can you please elaborate?

**Comment by lisp** [comment]
> On 2017-08-22, at 10:33, Elie Roux <notifications@github.com> wrote:
> 
> I'm sorry I think I got lost...
> 
> the point is that, as the recommendations permit and “best practice” suggests, the lexical processing layer should canonicalize.
> 
> Ok
> 
> in which case, the internal term lexical expression is the same for any case formulation of a given language tag.
> 
> how do you defined "internal term lexical expression"? I'm not sure I'm following... What I see in the RDF spec you pointed is:
> 
> Literal term equality: Two literals are term-equal (the same RDF literal) if and only if the two lexical forms, the two datatype IRIs, and the two language tags (if any) compare equal, character by character. Thus, two literals can have the same value without being the same RDF term. For example:
> 
>  "1"^^xs:integer
>  "01"^^xs:integer
> 
> denote the same value, but are not the same literal RDF terms and are not term-equal because their lexical form differs.
> 
> So it's pretty clear that they are not the same term…

no.
if the lexical layer is permitted to canonicalize, then they become the same term.

**Comment by eroux** [comment]
Well, this does not make any sense to me... I have two terms:

```
"foo"@EN
"foo"@en
```

the are different terms. I have a relation between terms which is clearly defined in RDF 1.1 as "term equality". There is another relation slightly less clearly defined in RDF 1.1 which is "value equality".

I agree that my two terms have "value equality". But they do not have "term equality". 

So let me try another angle: when I do RDF -> JSON-LD -> RDF, for each literal, I'm getting "term equality". Except for lang strings because the RDF->JSON-LD changes the term. And I think this is inconsistent with the rest of the transformations that keep "term equality".

I have not seen in any RDF-related specification a "canonical term equality" relationship that you seem to imply. Is it defined somewhere?

**Comment by eroux** [comment]
Another thing: it seems that what you imply (not taking into account RDF term equality, but also not canonicalizing all values), there is an improvement that could be done: BCP-47 specifies that the canonical form of a tag has the first letter of the script part upper-cased (ex: `zh-Latn-pinyin`), why not using that instead of lower-case? (I'm actually trying to use the BCP-47 canonical form in my dataset, but I don't want JSON-LD to mess everything up so I'll just use lower-case, which I find silly)

**Comment by lisp** [comment]
> On 2017-08-22, at 11:19, Elie Roux <notifications@github.com> wrote:
> 
> Well, this does not make any sense to me... I have two terms:
> 
> "foo"@EN
> "foo”@en

the sentence, "Lexical representations of language tags may be converted to lower case.” says that an implementation is permitted to create a state in which you have just one term.

> 
> the are different terms.

it is possible to read https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal to say, as noted above, that this is not necessarily the case.
there implementation reasons to take advantage of that permission.
gregg cited the same passage to you.

what does not make sense?

**Comment by lisp** [comment]
> On 2017-08-22, at 11:24, Elie Roux <notifications@github.com> wrote:
> 
> Another thing: it seems that what you imply (not taking into account RDF term equality, but also not canonicalizing all values),

no, not all values. just language tags.

> there is an improvement that could be done: BCP-47 specifies that the canonical form of a tag has the first letter of the script part upper-cased (ex: zh-Latn-pinyin), why not using that instead of lower-case?

rdf 1.1 does not offer that license.

> (I'm actually trying to use the BCP-47 canonical form in my dataset, but I don't want JSON-LD to mess everything up so I'll just use lower-case, which I find silly)

at your leisure.

**Comment by afs** [comment]
> Fuseki doesn't store terms, it only stores values

Other way round.  It stores terms as presented by the input. Users can make the input in the form they require. 

There is also an option to canonicalize lang tags (actually, by BCP-47 rules but that means the "value space of language tags" requirements, because it is functionally isomorphic with the lowercase form for comparison).

In places where values have been stored, (e.g. integer datatypes in TDB), some users then ask "why are my integers being changed?". There are two viewpoints.

The fact that RDF is not aligned with BCP-47 canonicalization does not help.

Preserving input and also indexing/comparing non-input form is very expensive for databases, in either execution time or implementation time.

**Comment by eroux** [comment]
After a few experiments, here is what I have noticed when using Fuseki, @afs tell me if I'm wrong:

- when using [DataAccessors](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/DatasetAccessor.html), lang tags are lower-cased when transformed into HTTP request, but integer values are not normalized. (is there an option for this behavior?)
- whatever the client, Fuseki returns `"1"^^xsd:integer` to a query, never `"1"^^xsd:nonNegativeInteger`. Am I wrong? Does it store the original input type somewhere?

In a more general perspective, I'm trying to wrap my head around all these different behaviors. Let me try to summarize what I understand:

The RDF 1.1 spec has two modes, depending on the use of the possibility offered by the `MAY` clause.

1. first mode: lang tags are lower-cased, and `"foo"@EN` and `"foo"@en` are term equals
2. second mode: lang tags are not lower-cased, and `"foo"@EN` and `"foo"@en` are not term equals

Then we have the following behaviors:
- JSON-LD uses the first mode
- Jena uses the second mode for most operations
- the [DataAccessors](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/DatasetAccessor.html) interface of Jena uses the first mode
- When canonicalizing literals, Jena uses a third custom mode which consists in converting tags to their BCP-47 canonical representation (ex: `zh-Latn-pinyin`)

Is it correct? If so, I propose that for the sake of simplicity Jena has an option to consistently use the first mode, instead of the custom third mode. That's the sense of my request in [JIRA-1377](https://issues.apache.org/jira/browse/JENA-1377?focusedCommentId=16136575&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16136575).

**Comment by afs** [comment]
Lang tags are not lower-cased on the HTTP request (unless you use JSON-LD in which case, jsonld-java is doing that). Jena never lower-cases language tags - the only point it changes them is, on request, when files are read via the parser option to canonicalize literals.

The datatype comment shows you are using TDB.  In TDB2, datatypes are preserved (by popular request).
