### ISSUE TITLE
JsonLd Expension vertexes and relations and nested vertexes

### ISSUE THREAD

**Issue by bartdotnet** [json-ld/json-ld.org#534]
Hi,

- question

the example document contains: a subject (a patent) (also Vertex), a relation (assignees) (also Edge), an object (assignee)(also Vertex); the object is also a vertex.

could expansion allow to the expand the nested Vertex (here assignee), assuming that a document only handles one main subject, would jsonLd create another child document for that purpose

current crafted context allows extraction of the assignees relation with the assignee object as an URI but omits the nested object vertex. Can a context be crafted in order not to lose the nested Vertex and treat it as a real subject this during for example the expansion process. If not, is there another process within the jsonLD specification that would allow this or will allow this in the future

- setting/ example

below example expresses a JsonLd document extracted via an manually "improvised" context based on Json obtained via an api of USPTO.gov and enriched by a context.

- context of the question: 

translating JsonLD to RDF and vica-versa

- additional information

below an example to represent the issue

below a - beit long - permalink to the JsonLD playground of the example

observation in the JsonLD playground: nested Vertex representation is hidden in all but the "Visualized" tab (need to click through though)

I could not find a direct answer in the logs or stackoverflow, my apologies if the question was answerred before. If so, please refer if possible.

Thanks in advance,
Regards,
Bart,

```
  {
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "patent": "http://dbpedia.org/ontology/patent",
    "patent_id": {
      "@id": "http://www.patentsview.org/api/patent/patent_id"
    },
    "patent_type": {
      "@id": "http://www.patentsview.org/api/patent/patent_type"
    },
    "patent_date": {
      "@type": "xsd:date",
      "@id": "http://www.patentsview.org/api/patent/patent_date"
    },
    "patent_title": {
      "@id": "http://www.patentsview.org/api/patent/patent_title"
    },
    "patent_abstract": {
      "@id": "http://www.patentsview.org/api/patent/patent_abstract"
    },
    "assignees": {
      "@id": "http://www.patentsview.org/api/patent/assignees",
      "@type": "@id"
    }
  },
    "patent_id": "5124989",
    "patent_date": "1992-06-23",
    "patent_type": "utility",
    "patent_title": "Method of debugging a computer program",
    "patent_abstract": "A method and system for recording debug commands as they are executed on a program is disclosed. The line number in the program reached after executing the debug command is also stored on the tape. The debug history tape is a sequential record of the debug commands. A user may reexecute one or more of the debug commands on the program by running the debug history tape. The user may stop the reexecution of the debug commands on a given line in the program generally in the area thought to contain the error, by moving an ending pointer to that region in the debug history tape. The tape will execute up to the ending pointer and then stop. The user may then examine the program, execute additional debug commands or take other action to locate the error. Any additional debug commands are also stored on the tape. The ability to reexecute the debug commands and stopping their execution at selected lines in the program aids the user in locating errors. After locating the errors, the user modifies the program. The user may then reexecute the same debug commands on the modified program to ensure that the error has been corrected.",
    "assignees": [
      {
        "assignee_organization": "Microsoft Corporation",
        "assignee_id": "237c2b0099548ddbfa5a37f07e0687ab",
        "assignee_type": "2",
        "@id": "http://www.patentsview.org/api/assignee/237c2b0099548ddbfa5a37f07e0687ab"
      }
    ],
    "@id": "http://www.patentsview.org/api/patent/5124989",
    "@type": "patent"
  }
```

https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22patent%22%3A%22http%3A%2F%2Fdbpedia.org%2Fontology%2Fpatent%22%2C%22patent_id%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2Fpatent_id%22%7D%2C%22patent_type%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2Fpatent_type%22%7D%2C%22patent_date%22%3A%7B%22%40type%22%3A%22xsd%3Adate%22%2C%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2Fpatent_date%22%7D%2C%22patent_title%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2Fpatent_title%22%7D%2C%22patent_abstract%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2Fpatent_abstract%22%7D%2C%22assignees%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2Fassignees%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22patent_id%22%3A%225124989%22%2C%22patent_date%22%3A%221992-06-23%22%2C%22patent_type%22%3A%22utility%22%2C%22patent_title%22%3A%22Method%20of%20debugging%20a%20computer%20program%22%2C%22patent_abstract%22%3A%22A%20method%20and%20system%20for%20recording%20debug%20commands%20as%20they%20are%20executed%20on%20a%20program%20is%20disclosed.%20The%20line%20number%20in%20the%20program%20reached%20after%20executing%20the%20debug%20command%20is%20also%20stored%20on%20the%20tape.%20The%20debug%20history%20tape%20is%20a%20sequential%20record%20of%20the%20debug%20commands.%20A%20user%20may%20reexecute%20one%20or%20more%20of%20the%20debug%20commands%20on%20the%20program%20by%20running%20the%20debug%20history%20tape.%20The%20user%20may%20stop%20the%20reexecution%20of%20the%20debug%20commands%20on%20a%20given%20line%20in%20the%20program%20generally%20in%20the%20area%20thought%20to%20contain%20the%20error%2C%20by%20moving%20an%20ending%20pointer%20to%20that%20region%20in%20the%20debug%20history%20tape.%20The%20tape%20will%20execute%20up%20to%20the%20ending%20pointer%20and%20then%20stop.%20The%20user%20may%20then%20examine%20the%20program%2C%20execute%20additional%20debug%20commands%20or%20take%20other%20action%20to%20locate%20the%20error.%20Any%20additional%20debug%20commands%20are%20also%20stored%20on%20the%20tape.%20The%20ability%20to%20reexecute%20the%20debug%20commands%20and%20stopping%20their%20execution%20at%20selected%20lines%20in%20the%20program%20aids%20the%20user%20in%20locating%20errors.%20After%20locating%20the%20errors%2C%20the%20user%20modifies%20the%20program.%20The%20user%20may%20then%20reexecute%20the%20same%20debug%20commands%20on%20the%20modified%20program%20to%20ensure%20that%20the%20error%20has%20been%20corrected.%22%2C%22assignees%22%3A%5B%7B%22assignee_organization%22%3A%22Microsoft%20Corporation%22%2C%22assignee_id%22%3A%22237c2b0099548ddbfa5a37f07e0687ab%22%2C%22assignee_type%22%3A%222%22%2C%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fassignee%2F237c2b0099548ddbfa5a37f07e0687ab%22%7D%5D%2C%22%40id%22%3A%22http%3A%2F%2Fwww.patentsview.org%2Fapi%2Fpatent%2F5124989%22%2C%22%40type%22%3A%22patent%22%7D&frame=%7B%7D&context=%7B%7D

**Comment by bartdotnet** [comment]
documentation at https://json-ld.org/spec/latest/json-ld/#expanded-document-form does not explain the above mentioned aspect

**Comment by gkellogg** [comment]
Hi @bartdotnet, the key point to understand is that JSON-LD is simply a serialization format, and is not involved in other semantic activities, such as creating documents for other nodes described within a JSON-LD document. Expansion is simply the elimination of the context so that all terms become fully expanded.

You might be interested in the [Linked Data Platform](https://www.w3.org/TR/ldp-primer/) which discusses how resources might be accessed and manipulated using different serialization formats, including JSON-LD. SPARQL Endpoints can also be queried to construct RDF documents (which also may be serialized as JSON-LD) based on the graph content.

You might also be interested in the [FHIR Project](http://hl7.org/implement/standards/fhir/summary.html), which also seeks to create a standard for exchanging healthcare information which may also be expressed in JSON-LD.

**Comment by bartdotnet** [comment]
Thanks for the feedback @gkellogg 

For me currently Json-LD is a great help for data integration in a semantic way. In this scenario I would start with non-linked data at transform it to linked data by adding a context and thus semantics. Note the semantics are relative as indeed sometimes improvised as not provided by an authoritative source or provider of the source information.

I also see Json-LD is also a potential bridge to mapping RDF to PG (Property Graph) stores. Based on the above I obtain the flexibility to transform the new obtained linked data to any compatible RDF representation and thus potentially target both RDF and PG stores

I kind of naively wanted to check if the Json-LD expansion process could be further used (or abused) to fully define subjects in a linked data in a limited recursive way for nested vertexes. 

I was inspired by a lecture of Brain Sletten see https://www.safaribooksonline.com/library/view/resource-oriented-architectures-linking/9781491924884/video219007.html describing some similar kinds of semantic hacks.

Your feedback is a good reality check how far I can go with this strategy.

I will check-out the sources cited by you as well.

Thanks,
Bart,

**Comment by bartdotnet** [comment]
Many thanks for the feedback
Regards,
Bart
