### ISSUE TITLE
Add expansion tests for empty `@base`.

### ISSUE THREAD

**Issue by davidlehn** [json-ld/json-ld.org#535]
Tests should be added for when `@base` is empty during expansion.  Apparently the behavior is untested, not well defined, and there has been discussion related to this in the past.  Perhaps this needs clarification in the spec too.

This came up due to a change in jsonld.js that changed the the output of expansion of the following:
```js
{
  "@context": {
    "@base": ""
  },
  "@type": "Type"
}
```
It used to result in:
```js
[{
  "@type": ["Type"]
}]
```
But now due to some RFC3986 fixes results in:
```js
[{
  "@type": ["/Type"]
}]
```
What should the output be?

**Comment by gkellogg** [comment]
Without looking in more detail at the spec, I think that if there is no `@base`, then it can't be used to make absolute IRIs. However, in almost all cases there will be some base, the only case where there's not is in something like the playground, where JSON is provided directly without any location.

The spec could address this, but it is pretty artificial; I'd say that relative IRIs do not expand to anything  other than themselves else if there is no base IRI. Alternatively, we set a default value for the base IRI to describe such behavior. In my distiller, I often assume `http://example.com/` as a default base.

No other test suites I can think of test for this, as the results are considered undefined.

**Comment by davidlehn** [comment]
Looking at this a bit more, according to the spec, `@base` MUST be a relative IRI, an absolute IRI, or null.  An empty string is none of those.  So perhaps implementations should just throw an "invalid base IRI" error.  jsonld.js mistakenly only allows null, absolute IRI, or an empty string.  It throws an error for a relative IRI `@base`.  I started to update test coverage for this.  At least jsonld.js will need some updating.

**Comment by gkellogg** [comment]
Is an empty string not a relative IRI? In any case, I don't think relative IRIs are vary useful. Perhaps it must resolve to an absolute IRI using the document base, for an inline context. This is consistent with the [spec text](https://json-ld.org/spec/latest/json-ld/#base-iri), but there is also provision for setting it to `null`, which implies that creating relative IRIs is okay.

> Setting `@base` to `null` will prevent relative IRIs to be expanded to absolute IRIs.

> Please note that the `@base` will be ignored if used in external contexts.

From RFC 3986:

      URI-reference = URI / relative-ref

      relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

      relative-part = "//" authority path-abempty
                    / path-absolute
                    / path-noscheme
                    / path-empty

      path-empty    = 0<pchar>

So, a URI reference can be a relative-ref, which can have just a relative-part, which can be path-empty, which is the empty string.

**Comment by davidlehn** [comment]
Apparently I was reading Ye Olde RFC text where empty relative uris were not allowed.  Seems to be ok in the last few decades. ;-)

I currently have no opinion on relative or empty base being useful or not.  I just think that since they are allowed the test suite should cover them so all implementations produce the same output.

**Comment by davidlehn** [comment]
Tests have been added.
