### ISSUE TITLE
Mixing differently typed nodes for a property

### ISSUE THREAD

**Issue by backbone87** [json-ld/json-ld.org#538]
In the spec under point 6.2 https://json-ld.org/spec/latest/json-ld/#node-objects the following is said:
>  The values associated with keys that expand to an absolute IRI must be one of the following: [...] - an array of zero or more of the possibilities above,

I am not quite sure, if this allows something like this:
```json
{
  "http://example.com/name": [
    "Michael",
    42,
    { "@value": "Mike" }
    { "@id": "http://example.com/Michael" }
  ]
}
```

Is this kind of mixing allowed? I am quite new to the Json-LD data model and this section of the spec can be understood as "there can be multiple nodes of a property, but they must be of one type".

**Comment by elf-pavlik** [comment]
Unfortunately https://json-ld.org/playground/ seems broken at this moment but you can also test your snippets with http://linter.structured-data.org/ You just need to surround it with `<script type="application/ld+json"></script>`
```html
<script type="application/ld+json">
{
  "http://example.com/name": [
    "Michael",
    42,
    { "@value": "Mike" },
    { "@id": "http://example.com/Michael" }
  ]
}
</script>
```

As far as I can tell your snippet looks like valid JSON-LD. Once JSON-LD playground starts working again you can use it to see expanded version as well as N-Quads to make sure that you get intended results. Meanwhile you can also try out any of the JSON-LD compliant implementations listed on https://json-ld.org/#developers

**Comment by gkellogg** [comment]
You can also try [my distiller](http://rdf.greggkellogg.net/distiller?command=expand&format=jsonld&output_format=jsonld), which is up-to-date with the 1.1 JSON-LD algorithms.

In this case, yes, a property (expanding to an absolute IRI) can have multiple values, consisting of value-objects, node-objects, or other JSON scalar types, which are interpreted based on possible context information associated with the property.

The distiller uses the same code as the linter, but accepts a wider variety of input formats.

**Comment by backbone87** [comment]
Thanks for the clarification. Idk, if its worth changing the wording in the spec to make this one more obvious. For me as a non native english speaker, it was not immediately clear, how this statement was meant.
If you fell alright about the wording, feel free to close this one

**Comment by gkellogg** [comment]
I'm afraid it seems pretty clear to me, as it's quite explicit about exactly what the value of such a key can be. Please suggest wording that you believe would improve it.

Alternatively, we could add an example of a property with such heterogenous values.

**Comment by azaroth42** [comment]
:+1: to adding an example with differently typed values.
