### ISSUE TITLE
Missing tests for Node Identifier Indexing and Node Type Indexing

### ISSUE THREAD

**Issue by miguel76** [json-ld/json-ld.org#541]
In the test-suite there are no tests relevant neither to [Node Identifier Indexing](https://json-ld.org/spec/latest/json-ld/#node-identifier-indexing) (`"@container": "@id"`) nor [Node Type Indexing](https://json-ld.org/spec/latest/json-ld/#node-type-indexing) (`"@container": "@type"`).

**Comment by gkellogg** [comment]
See the Expansion tests m001-m007 and Compaction tests m001-m006.

Expansion m001 test input:

```json
{
  "@context": {
    "@vocab": "http://example/",
    "idmap": {"@container": "@id"}
  },
  "idmap": {
    "http://example.org/foo": {"label": "Object with @id <foo>"},
    "_:bar": {"label": "Object with @id _:bar"}
  }
}
```

Expected results:

```json
[{
  "http://example/idmap": [
    {"http://example/label": [{"@value": "Object with @id _:bar"}], "@id": "_:bar"},
    {"http://example/label": [{"@value": "Object with @id <foo>"}], "@id": "http://example.org/foo"}
  ]
}]
```
