### ISSUE TITLE
over aggressive prefix expansion of terms

### ISSUE THREAD

**Issue by mhalle** [json-ld/json-ld.org#552]
I have a JSON-LD playground example that shows a bug in prefix expansion of terms. 

http://tinyurl.com/yas45wss

Two problematic terms are defined, "source" and "sourceWSuffix", along with one control term "name".  When "source" is compacted, it is misidentified as a prefix.  This somehow causes "sourceWSuffix" to become "source:WSuffix" (which seems overaggressive). 

Also, "source" and "sourceWSuffix" both have "@id" values declared in the context that are lost in expansion:  their expanded values are "items:that" (interpretation as a string) rather than undergoing IRI expansion as they should ("https://exmpl.com/items/that").

I would assume this is a library implementation bug.  Defect appears in the playground and in the python implementation, at least.

**Comment by gkellogg** [comment]
The 1.0 spec pretty much allows any term to be used as a prefix, so this is not an implementation bug, but a "feature" of the 1.0 specification. This is being tightened up in 1.1 to restrict the terms that can be used as prefixes See #405 and 59f0f3135371ef01e20fcf4214b10e7805b8c64d. The new spec text from [Compact IRIs](https://json-ld.org/spec/latest/json-ld/#compact-iris) reads as follows:

> When processing mode is set to json-ld-1.1, terms will be used as compact IRI prefixes when compacting only if their expanded term definition contains a @prefix member with the value true, or if it has a a simple term definition where the value ends with a URI gen-delim character (e.g, /, # and others, see [RFC3986]).

Changes were made to affect 1.0 implementations, but that might not have made it into the playground:

> In JSON-LD 1.0, terms will be used as compact IRI prefixes when compacting only if they map to a value that ends with a URI gen-delim character (e.g, /, # and others, see [RFC3986]).

**Comment by mhalle** [comment]
Confirmed that the python implementation has this "unexpected behavior".

Can you tell me which implementations were tightened up?  I could take a stab at fixing the python impl.

**Comment by gkellogg** [comment]
The [Ruby Implementation](https://github.com/ruby-rdf/json-ld) has it, which you can check on the [Ruby RDF Distiller](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=jsonld).
