### ISSUE TITLE
inconsistent compaction between fields with literal and @id values

### ISSUE THREAD

**Issue by mhalle** [json-ld/json-ld.org#553]
I have two fields that are identical except for the fact that one takes a literal value, the other takes an "@id" type.

http://tinyurl.com/yadba2pw

When compacting, the name of the literal valued field is correctly compacted. The field with the "@id" value, however, is not compacted.

**Comment by gkellogg** [comment]
@mhalle this operating normally. In your example, values in the first object are treated as literals, even though https://exmpl.com/field1 has the form of an IRI. When compacting, it can't use `field1`, as it's value is a literal, not a URI. It needs to expand to an IRI for compaction to select a term which allows it to be expressed as a simple string.

See http://tinyurl.com/y8yumdef.
