### ISSUE TITLE
Document license -> w3c permissive software and document license?

### ISSUE THREAD

**Issue by cwebber** [json-ld/json-ld.org#560]
If we switched the license officially to the [w3c permissive software and document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) that may be a good idea, especially since we are describing algorithms and it would be nice to be able to copy and paste sections of the spec text into comments.

**Comment by gkellogg** [comment]
We'll take this up on a call we're trying to schedule. Please consider joining, Doodle poll is https://doodle.com/poll/x9whhs5b34ih7ytq and we need more respondants.

**Comment by gkellogg** [comment]
@lanthaler general agreement to accept this, do you have any issues with it?

**Comment by gkellogg** [comment]
[RESOLUTION: accept issue 560 pending lanthaler approval ](https://json-ld.org/minutes/2018-01-08/#resolution-2)
