### ISSUE TITLE
Misnamed argument in call to IRI compaction algorithm?

### ISSUE THREAD

**Issue by cwebber** [json-ld/json-ld.org#562]
Maybe I'm confused, but in the IRI compaction algorithm, there's a reference to calling the IRI compaction algorithm apparently recursively:

> If the result of using the IRI compaction algorithm, passing active context, inverse context, the value associated with the @id key in value for iri, true for vocab, and true for document relative has a term definition in the active context with an IRI mapping that equals the value associated with the @id key in value, then append @vocab, @id, and @none, in that order, to preferred values.

Except it says "true for document relative", which afaict isn't an argument of the IRI Compaction algorithm.  My guess is this is supposed to be "reverse"?

This is the case in both 1.0 and the latest community group report.

**Comment by gkellogg** [comment]
Your correct, that there is no such flag. How’re, it should never not be _reverse_. I’ll fix this in the 1.1 version.
