### ISSUE TITLE
Grouping of ands and ors in IRI compaction algorithm

### ISSUE THREAD

**Issue by cwebber** [json-ld/json-ld.org#563]
> If either compact IRI is null or candidate is shorter or the same length but lexicographically less than compact IRI and candidate does not have a term definition in active context or if the term definition has an IRI mapping that equals iri and value is null, set compact IRI to candidate.

That's a lot of ands and ors, but they aren't clearly grouped.  Maybe use parentheses or square brackets to do grouping?

At the very least, mind sharing the appropriate grouping here? ;)

**Comment by cwebber** [comment]
Here's my attempt to make sense of the and/or grouping.  Does this look about right?

``` scheme
  (when (and (or (eq? compact-iri 'null)
                 (< (string-length candidate) (string-length compact-iri))
                 (and (= (string-length candidate) (string-length compact-iri))
                      (string< candidate compact-iri)))
             (or (not (active-context-terms-assoc candidate active-context)
                      (and (equal? iri-mapping iri)
                           (eq? value 'null)))))
    (set! compact-iri candidate))
```

**Comment by gkellogg** [comment]
IMO, it could probably use with some more punctuation (commas and semicolons), but the language is reasonably precise. Some examples would usefully clarify this, with explanatory text to describe the different branch options.

**Comment by cwebber** [comment]
commas and semicolons would help

**Comment by gkellogg** [comment]
@cwebber see #575.
