### ISSUE TITLE
Limit use of @none in maps to 1.1 mode

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#571]
As discussed in https://github.com/json-ld/json-ld.org/pull/569#issuecomment-359598061, to avoid backwards-compatibility issues when compacting, the use of `@none` and in term selection should be limited to 1.1 mode.

**Comment by davidlehn** [comment]
@gkellogg Note there is a misuse of `<p>` tags in the merged commit that needs to be fixed.

**Comment by gkellogg** [comment]
I added tests I thought were useful, but don't think I added a negative test for 1.0. If you think it necessary, we can add it, but I believe we already have tests for language and index that show that they don't use a dictionary in 1.0 mode.
