### ISSUE TITLE
Settings/Options to treat CURIE as one value rather than (prefix:value)

### ISSUE THREAD

**Issue by kevinxin90** [json-ld/json-ld.org#580]
I have use case here where the value of one of the JSON field contains a colon in it. The JSON doc looks something like this {"do": "DOID:1234"}. Although the value has a coIon in it, itself is indeed an ID rather than a CURIE. And I would like to expand the value to "http://identifiers.org/doid/DOID:1234". However, based on my knowledge, I don't see JSON-LD offers a way to do it.
I tried a couple of different JSON-LD context here:
TEST 1 (using @context, @base)
`{
   "@context":{
      "@version":1.1,
      "doid":{
         "@type":"@id",
         "@id":"http://identifiers.org/associatedWithDisease",
         "@context":{
            "@base":"http://identifiers.org/doid/"
         }
      }
   },
   "doid":"DOID:1234"
}`
Output(nquads):
`_:b0 <http://identifiers.org/associatedWithDisease> <DOID:1234> .`

Test 2:
`{
   "@context":{
      "@version":1.1,
      "DOID":"http://identifiers.org/doid",
      "doid":{
         "@type":"@id",
         "@id":"http://identifiers.org/associatedWithDisease"
      }
   },
   "doid":"DOID:1234"
}`
Output (nquads):
`_:b1 <ont:associatedWithDisease> <http://identifiers.org/doid/1234>`

So it seems JSON-LD either chose to leave it alone and return 'DOID:1234', or chose to take it a CURIE and return 'http://identifiers.org/doid/1234'. But with no way to return 'http://identifiers.org/doid/DOID:1234'.

Wondering if anyone knows a solution for this?

Thanks!

Best,
Kevin

**Comment by azaroth42** [comment]
I assume that you can't define "DOID:1234" in your context, as the 1234 will change for different instances. However, can you define DOID?

eg:

```
{
  "@context": {
    "DOID": "http://identifiers.org/doid/DOID:",
    "do": {"@type": "@vocab", "@id": "http://example.org/property"}
  },
  "do": "DOID:1234"
}
```

Works as desired.

**Comment by kevinxin90** [comment]
@azaroth42 Hi Rob, Thanks so much for the answer! That perfectly solves my problem!!!! Thank you!
