### ISSUE TITLE
Revisit empty string as term

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#584]
JSON-LD has a restriction that terms must not be the empty string

From [JSON-LD Syntax 6.1](https://json-ld.org/spec/latest/json-ld/#terms-0):

> Furthermore, the term MUST NOT be an empty string ("") as not all programming languages are able to handle empty JSON keys.

IIRC, this was added due to an issue in an earlier version of PHP, and I suspect it is no longer an issue. Furthermore, the use of empty prefixes is common in other RDF syntaxes, so allowing it here for 1.1 documents would be reasonable, if tooling supports it.

As evidence, consider [this stackoverflow question](https://stackoverflow.com/questions/48573967/compact-iri-with-an-empty-string-prefix-can-it-be-done).

Also, note that while the syntax document makes such a normative statement, the API algorithms don't call this out as an error condition.

**Comment by azaroth42** [comment]
@dlongley traced this issue back here:
> https://github.com/json-ld/json-ld.org/issues/480#issuecomment-294170927

I think the bigger question is around semantics of its use in the various places it might be used.

**Comment by gkellogg** [comment]
Deferred to WG due to https://json-ld.org/minutes/2018-04-10/#resolution-3.

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/12.
