### ISSUE TITLE
Framing and @reverse

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#588]
Further to #311, should the predicate that triggered the use of an `@reverse` property in a frame be removed from its resource to avoid a necessarily circular reference?

For example, if the data shape is:

X includes Y
Z is Y
Z in X

And there's a @reverse of "in" called "proxies" which is then @embed always via a Frame, should the Z resources also have in back to X?

I would have expected:

```
{
  "id": "X",
  "includes":  ["Y"],
  "uses": [{"id": "Z", "is": "Y"}]
}
```

But instead the `in` property is still present in Z.

Use Case:  http://openarchives.org/ore/0.9/jsonld#proxies

**Comment by gkellogg** [comment]
@azaroth42 could you come up with a specific, minimal example which illustrates the issue? You might use [my distiller](http://rdf.greggkellogg.net/distiller?command=frame&format=jsonld&output_format=jsonld) as a way of expressing the actual behavior, at least until the last bits of framing support are in the playground.

**Comment by azaroth42** [comment]
Input JSON-LD:
```
{
  "@context": {
    "eg": "https://example.org/ns/",
    "reversed": {"@reverse": "eg:forwards", "@type": "@id"},
    "forwards": {"@id": "eg:forwards", "@type": "@id"},
    "Thing": {"@id": "eg:Thing"}
  },
  "@graph": [
    {
      "@id": "http://example.com/1",
      "@type": "Thing"
     },
    {
      "@id": "http://example.com/2",
      "@type": "Thing",
      "forwards": "http://example.com/1"
    }
  ]
}
```

Input Frame:

```
{
  "@context": {
    "eg": "https://example.org/ns/",
    "reversed": {"@reverse": "eg:forwards", "@type": "@id"},
    "forwards": {"@id": "eg:forwards", "@type": "@id"},
    "Thing": {"@id": "eg:Thing"}
  },
  "@id": "http://example.com/1",
  "reversed": {"@embed": "@always"}
}
```

Output JSON-LD:

```
{
  "@context": {
    "eg": "https://example.org/ns/",
    "reversed": {
      "@reverse": "eg:forwards",
      "@type": "@id"
    },
    "forwards": {
      "@id": "eg:forwards",
      "@type": "@id"
    },
    "Thing": {
      "@id": "eg:Thing"
    }
  },
  "@graph": [
    {
      "@id": "http://example.com/1",
      "@type": "Thing",
      "reversed": {
        "@id": "http://example.com/2",
        "@type": "Thing",
        "forwards": "http://example.com/1"
      }
    }
  ]
}
```

Note the presence of both `reversed` and `forwards`, which is encoding the same triple (1 forwards 2) twice.

**Comment by gkellogg** [comment]
@azaroth42 doesn't look like this was ever resolved or put into the framing spec, do you want to replicate it over there?

**Comment by tanuja3088** [comment]
Yes I am also facing an issue regarding the same, About
attached sample input and frame
[sample.zip](https://github.com/json-ld/json-ld.org/files/4616267/sample.zip)

**Comment by gkellogg** [comment]
It's not an error to include this triple, but you can construct a frame which will eliminate it ([playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22eg%22%3A%22https%3A%2F%2Fexample.org%2Fns%2F%22%2C%22reversed%22%3A%7B%22%40reverse%22%3A%22eg%3Aforwards%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22forwards%22%3A%7B%22%40id%22%3A%22eg%3Aforwards%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22Thing%22%3A%7B%22%40id%22%3A%22eg%3AThing%22%7D%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fexample.com%2F1%22%2C%22%40type%22%3A%22Thing%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fexample.com%2F2%22%2C%22%40type%22%3A%22Thing%22%2C%22forwards%22%3A%22http%3A%2F%2Fexample.com%2F1%22%7D%5D%7D&frame=%7B%22%40context%22%3A%7B%22eg%22%3A%22https%3A%2F%2Fexample.org%2Fns%2F%22%2C%22reversed%22%3A%7B%22%40reverse%22%3A%22eg%3Aforwards%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22forwards%22%3A%7B%22%40id%22%3A%22eg%3Aforwards%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22Thing%22%3A%7B%22%40id%22%3A%22eg%3AThing%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2F1%22%2C%22reversed%22%3A%7B%22%40embed%22%3A%22%40always%22%2C%22%40explicit%22%3Atrue%7D%7D)):

```json
{
  "@context": {
    "eg": "https://example.org/ns/",
    "reversed": {"@reverse": "eg:forwards", "@type": "@id"},
    "forwards": {"@id": "eg:forwards", "@type": "@id"},
    "Thing": {"@id": "eg:Thing"}
  },
  "@id": "http://example.com/1",
  "reversed": {
    "@embed": "@always",
    "@explicit": true
  }
}
```

**Comment by tanuja3088** [comment]
Hi, I quite a dint understand what changes I need to do in the frame as per my sample example?

{
   "@context":{
      "test":"http://example/test#",
     "test:hasPart":{"@reverse": "test:hasUnlockRequestObject"}
   },
  
   "test:hasUnlockRequestObjectChangeLog":{
    
      "test:hasUnlockRequest":{}      
   } ,"test:hasPart":{
        "@embed":"@always"     
      }
}

**Comment by gkellogg** [comment]
I added `"@explicit": true` to the "reversed" property, so that it only emits those properties explicitly listed.

**Comment by tanuja3088** [comment]
òk

**Comment by gkellogg** [comment]
I can't parse your example, as there may be encoding issues. Can you send a (shortened) link to the playground with your example loaded?

**Comment by tanuja3088** [comment]
Here is the URL,  the output I get of Playground is not that I get from the jsonld-java

https://tinyurl.com/yd55h8d3

**Comment by gkellogg** [comment]
jsonld-java may not support `@reverse` in frames yet. It's a new feature in 1.1.

**Comment by tanuja3088** [comment]
ahh ok
