### ISSUE TITLE
JSON-LD version on playground

### ISSUE THREAD

**Issue by davidlehn** [json-ld/json-ld.org#589]
During the last meeting it was [resolved](https://json-ld.org/minutes/2018-02-05/#resolution-1) to have one playground for 1.0 and 1.1 processing.  Some notes on that related to [jsonld.js](https://github.com/digitalbazaar/jsonld.js):

- 0.4.x passes older 1.0 test suites
- 0.4.x does not pass more recent tests added for 1.0
- 0.5.x does pass all current 1.0 tests
- 0.5.x also includes a bit of 1.1 functionality, in particular some `@graph` handling and a bit of `@version` handling
- 0.6.x should end up passing all 1.0 and current 1.1 draft tests
- there *may* be technical issues using multiple jsonld.js versions on one page

From an ease of site development viewpoint, I think we should just put the most recent jsonld.js on the playground and add a UI control to pick the `processingMode` API option.  Due to practicalities of jsonld.js not having a full correct 1.0 *only* lib, it seems not worth the effort to try and deal with this any other way.  There are edge cases where a 1.1 lib in 1.0 mode will produce different results than a 1.0 lib.  My guess is that in practice this really doesn't matter.  Or in any case, is not worth handling on the playground.

**Comment by lanthaler** [comment]
Wouldn't the easiest be if we would simply have two HTML pages for the two versions and make them include different versions?

**Comment by davidlehn** [comment]
We have two versions now.  There's the main one with 0.5.x lib, and dev one with ~0.6.x lib.  But as I was saying, there is no fully conforming 1.0 lib available.  I doubt anyone wants to spend effort to make that happen vs just using 1.1 in 1.0 mode and accept the issues.  I'm not too convinced it's even a real issue that people would want a 1.0 only playground.

**Comment by dlongley** [comment]
Regarding having multiple playgrounds, here are my thoughts:

At a minimum, the main playground should have a toggle for processing mode (1.0 vs. 1.1), and it should use the same (most recent) lib.

*If* people feel a need for a second playground that will process things using some older version of the library (i.e. pre-1.1 ... but even here expectations about what it will do may be off) then it can be a separate HTML page that loads that older version.

**Comment by gkellogg** [comment]
We do have multiple playgrounds, and it does allow selecting the processing mode. Closing.
