### ISSUE TITLE
Native support for schema:ListItem

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#595]
Per a suggestion by @danbri, we may want to add a container type, similar to `@list` for encoding [`schema:ItemList`](http://schema.org/ItemList) serializations, when the values are [`schema:ListItem`](http://schema.org/ListItem) and order is set through `schema:position`. `ItemList` can be used with text values as well, but this is already reasonably supported natively.

Markup might look like the following:

```json
{
  "@context": {
    "@vocab": "http://schema.org/",
    "itemListElement": {"@container": "@listItem"}
  },
  "@type": "ItemList",
  "@url": "http://en.wikipedia.org/wiki/Billboard_200",
  "name": "Top music artists",
  "description": "The artists with the most cumulative weeks at number one according to Billboard 200",
  "itemListElement": [
    {"@type": "MusicGroup", "name": "Beatles"},
    {"@type": "MusicGroup", "name": "Elvis Presley"},
    {"@type": "MusicGroup", "name": "Michael Jackson"},
    {"@type": "MusicGroup", "name": "Garth Brooks" }
  ]
```

This would expand to the following:

```json
[
  {
    "@id": "http://en.wikipedia.org/wiki/Billboard_200",
    "@type": ["http://schema.org/ItemList"],
    "http://schema.org/description": [{
      "@value": "The artists with the most cumulative weeks at number one according to Billboard 200"
    }],
    "http://schema.org/itemListElement": [{
      "@type": ["http://schema.org/ListItem"],
      "http://schema.org/item": [{
        "@type": ["http://schema.org/MusicGroup"],
        "http://schema.org/name": [{"@value": "Beatles"}]
      }],
      "http://schema.org/position": [{"@value": 1}]
    },  {
      "@type": ["http://schema.org/ListItem"],
      "http://schema.org/item": [{
        "@type": ["http://schema.org/MusicGroup"],
        "http://schema.org/name": [{"@value": "Elvis Presley"}]
      }],
      "http://schema.org/position": [{"@value": 2}]
    }, {
      "@type": ["http://schema.org/ListItem"],
      "http://schema.org/item": [{
        "@type": ["http://schema.org/MusicGroup"],
        "http://schema.org/name": [{"@value": "Michael Jackson"}]
      }],
      "http://schema.org/position": [{"@value": 3}]
    }, {
      "@type": ["http://schema.org/ListItem"],
      "http://schema.org/item": [{
        "@type": ["http://schema.org/MusicGroup"],
        "http://schema.org/name": [{"@value": "Garth Brooks"}]
      }],
      "http://schema.org/position": [{"@value": 3}]
    }
  ],
  "http://schema.org/name": [{"@value": "Top music artists"}]
}]
```

Otherwise, it works like `@list`.

When compacting, the processor will re-order items based on `position`, and ignore any `nextItem` or `previousItem` entries.

Expansion shows 1-base position, but could be 0-base as well. Note that specific `position` values are lost when compacting, and duplicate values may lead to undefined relative ordering.

**Comment by workergnome** [comment]
Is there any reason to explicitly add that functionality for Schema itemLists, as opposed to, say, ORE Aggregations with ordered proxies or ActivityStream OrderedCollections?  

We've got lots of different patterns for ordering RDF sets across many ontologies, and I worry that blessing more than one (which we have with `rdf:List`) means that we'd need a good reason not to bless them all.

**Comment by gkellogg** [comment]
Aside from the politics of gaining support for a WG, most current use of JSON-LD on the web _is_ for schema.org.

There are certainly other useful ontologies, and if someone shows up with a compelling use case and evidence of the impact it would make, we would likely consider.

However, this is a valid concern.

**Comment by dlongley** [comment]
Seems like you could do something more general like:

```js
"itemListElement": {
  "@container": {
    "@type": "@itemList",
    "@itemType": "http://schema.org/ListItem",
    "@itemProperty": "http://schema.org/itemListElement"
    "@itemPosition": "http://schema.org/position"
  }
}
```

Provided that there's a common pattern for these types of "item list" containers.

**Comment by gkellogg** [comment]
@dlongley is on to something, although more generic keywords might be useful, basically support common patterns in indirect containers, such as `listItem`, Ordered Link Ontology, and others.

Examining Turtle representations of these lists:

## [schema:ItemList](http://schema.org/ItemList)
```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://example.com/dresses> schema:name "Dresses" .

<https://example.com/dresses/real> schema:name "Real Dresses" .

 [
     a schema:BreadcrumbList;
     schema:itemListElement [
       a schema:ListItem;
       schema:item <https://example.com/dresses>;
       schema:position 1
     ],  [
       a schema:ListItem;
       schema:item <https://example.com/dresses/real>;
       schema:position 2
     ]
 ] .
```

This uses an indirection to a `ListItem` referenced from an `itemListElement`, referencing the ordered resource using `item`. Ordering is indicated by `position`. `itemListElement` is a property of `ItemList`, or a derivative class. The size of the list may be indicated using `numberOfItems`, and individual `ListItems` may be linked together using `nextItem` and `previousItem`.

Interestingly, each `ListItem` caries out a similar purpose as [`schema:Role`](http://schema.org/Role), and in a parallel universe, a `ListItem` might have been a kind of `Role`, and linkage would be performed based on parallel incoming and outgoing properties.

## [Ordered List Ontology](http://smiy.sourceforge.net/olo/spec/orderedlistontology.html)
```turtle
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix dc:      <http://purl.org/dc/elements/1.1/> .
@prefix olo:     <http://purl.org/ontology/olo/core#> .
@prefix mo:      <http://purl.org/ontology/mo/> .
@prefix ex:      <http://example.org/> .
 
ex:FunkyPlaylist a olo:OrderedList ;
   dc:title "Funky Playlist" ;
   dc:description "A playlist full of funky legends" ;
   dc:creator <http://foaf.me/zazi#me> ;
      olo:length 2 ;
      olo:slot [   
         olo:index 1 ;
         olo:item ex:SexMachine
      ] ;
      olo:slot [
         olo:index 2 ;
         olo:item ex:GoodFoot
      ] .
 
ex:SexMachine a mo:Track ;
   dc:title "Sex Machine" ;
   dc:creator <http://dbpedia.org/resource/James_Brown> .
 
ex:GoodFoot a mo:Track ;
   dc:title "Good Foot" .
```

This uses an indirection to a `Slot ` referenced from an `slot `, referencing the ordered resource using `item`. Ordering is indicated by `index`. `slot` is a property of `OrderedList`, or a derivative class. The size of the list may be indicated using `length`, and individual `ListItems` may be linked together using `next` and `previous`.

## [ORE Specification](http://www.openarchives.org/ore/1.0/datamodel)
ORE defines a _Proxy_ type, which can serve as an intermediary between resources. While it doesn't define an ordering directly, a hypothetical `xyzzy:hasNext` predicate could be used to link _Proxy_ resources to each other.

```turtle
@prefix ore: <http://www.openarchives.org/ore/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xyz: <http://example/xyz/> .

<ReM-1> a ore:ResourceMap ;
  ore:describes <A-1> .

<A-1> a ore:Aggregation ;
  ore:isDescribedBy <ReM-1> ;
  ore:aggregates <AR-1>, <AR-2> .

<P-1> a ore:Proxy ;
  ore:proxyFor <AR-1> ;
  ore:proxyIn <A-1> ;
  xyz:hasNext <P-2> .

<P-2> a ore:Proxy ;
  ore:proxyFor <AR-2> ;
  ore:proxyIn <A-1> .

<AR-1> a rdf:Resource .
<AR-2> a rdf:Resource .
```

Note that the proxies have an inverse relationship to their aggregation, and that the _Aggregation_ is an additional intermediate object from the _ResourceMap_.

Ordering between proxies is not directly defined, and this describes a form of reification similar to `schema:Role`. Analogies with _OLO_ and _ItemList_ are quite different, and this is likely not suitable for JSON-LD syntactic sugar.

## [ActivityStream Ordered Collections](https://www.w3.org/TR/activitystreams-core/#dfn-orderedcollection)
The Ordered Collection is done using existing JSON-LD `@list` support using an `orderedItem` term having `@container: @list`. The following JSON-LD example is rendered in Turtle to illustrate:

```jsonld
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "Object history",
  "type": "OrderedCollection",
  "totalItems": 2,
  "orderedItems": [
    {
      "type": "Create",
      "actor": "http://www.test.example/sally",
      "object": "http://example.org/foo"
    },
    {
      "type": "Like",
      "actor": "http://www.test.example/joe",
      "object": "http://example.org/foo"
    }
  ]
}
```

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <https://www.w3.org/ns/activitystreams#> .

 [
     a as:OrderedCollection;
     as:items ([
         a as:Create;
         as:actor <http://www.test.example/sally>;
         as:object <http://example.org/foo>
       ] [
         a as:Like;
         as:actor <http://www.test.example/joe>;
         as:object <http://example.org/foo>
       ]);
     as:summary "Object history";
     as:totalItems "2"^^xsd:nonNegativeInteger
 ] .
```

Consequently, the ActivityStreams Ordered Collection doesn't introduce any new intervening resources.

## Conclusions
Both _ItemList_ and _OLO_ use similar paradigms with intermediaries used to describe ordered relationships, however given common authorship (@danbri), that's not too unusual. But, this does offer a generalizable mechanism for describing such relationships, without binding directly to any particular vocabulary. @dlongley's example might be re-stated with more generic keywords:

```jsonld
"itemListElement": {
  "@container": {
    "@type": "http://schema.org/ListItem",
    "@item": "http://schema.org/item"
    "@position": "http://schema.org/position",
    "@next": "http://schema.org/nextItem",
    "@previous": "http://schema.org/previousItem"
  }
}
```

In this case, the fact that `@container` is an object signals that such an indirect mechanism is to be used, and the keyword attributes describe the properties of the intermediate resource used to connect. It does not describe properties of the containing resource, such as `numberOfItems`.

**Comment by danbri** [comment]
(fwiw I didn't work on OLO)

Baking in just schema.org feels a bit off. But it is certainly true that JSON-LD's use of JSON arrays for property repetition confuses audiences who don't simultaneously understand JSON's initial flaws regarding field repetition and also RDF's need for explicit order.

**Comment by gkellogg** [comment]
Deferred to WG due to https://json-ld.org/minutes/2018-04-10/#resolution-3.

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/15.
