### ISSUE TITLE
blank node identifier pruning when @id aliased

### ISSUE THREAD

**Issue by eroux** [json-ld/json-ld.org#611]
It seems quite common these days to have an alias for @id in a jsonld context (see http://schema.org/docs/jsonldcontext.json ). The spec on json-ld.org [specifies](https://json-ld.org/spec/latest/json-ld-framing/#dfn-pruneblanknodeidentifiers) that:

```
pruneBlankNodeIdentifiers
    Removes @id from node objects where the value is a blank node identifier used only once within the document.
```

maybe the spec could specify that if the `@id` field is aliased in the `@context`, then `pruneBlankNodeIdentifiers` should remove the alias? Or would that be implicit?

See also https://github.com/jsonld-java/jsonld-java/issues/226

**Comment by gkellogg** [comment]
In the algorithm, pruning happens before compaction, where keyword aliases are applied. The text _could_ read “... `@id` (or alias) ...”, but IMHO, this gets cumbersome. Perhaps a catch all statement in the How to Read this Document section such as the following might help:

> Throughout this document, if an operation is described on a *keyword* that operation also applies to any term used as an alias of that keyword.

**Comment by eroux** [comment]
I think that could help yes... but if the spec already implies that, maybe just a test about that particular case would be enough?
