### ISSUE TITLE
Remaining pruneBlankNodeIdentifiers test options.

### ISSUE THREAD

**Issue by davidlehn** [json-ld/json-ld.org#635]
`frame-manifest.jsonld` still has a few tests with the `"pruneBlankNodeIdentifiers": false` option.  This was removed in https://github.com/json-ld/json-ld.org/pull/629.  How should this be handled?  @dlongley suggested the flag may be useful in 1.0 mode.  Should those tests stay around and be marked as 1.0?  If so then it seems implementations would have to know how to handle a flag which has no spec text.  If the tests are removed then how do implementations test that flag?

**Comment by gkellogg** [comment]
No, the flag’s gone, so we should make these depend on the processing mode, which can be set in the manifest.

Implementations May keep such a flag, but the CG manifest won’t reflect this.

**Comment by gkellogg** [comment]
These are removed in PR #643.
