### ISSUE TITLE
Framing: expected behavior for @explicit/@embed/@default

### ISSUE THREAD

**Issue by pjohnston-wiley** [json-ld/json-ld.org#641]
Apologies in advance if this turns out to be covered by the spec, but i was unable to determine it from the latest draft or the issues on github. In summary, I am trying to understand how the various switches in framing can be used at different levels to control output, in particular how `@explicit` and `@embed` are supposed to interact with each other. I appear to be running into some inconsistencies, and I would just like to understand if these are just bugs in the current  implementation, or i am missing the intent. Thanks for your patience.

I have been mostly testing with pyld (i have large files to process, and i would be happy to have a go at fixing it there), though i can reproduce the behavior in both the dev and stable playgrounds. [This example](https://json-ld.org/playground-dev/#startTab=tab-framed&copyContext=true&json-ld=%7B%22%40context%22%3A%7B%22%40language%22%3A%22en%22%2C%22ex%22%3A%22http%3A%2F%2Fexample.com%2F%22%2C%22termStatus%22%3A%7B%22%40id%22%3A%22ex%3AtermStatus%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22unstable%22%3A%22ex%3Aunstable%22%2C%22stable%22%3A%22ex%3Astable%22%2C%22termSupersedes%22%3A%7B%22%40id%22%3A%22ex%3AtermSupersedes%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22label%22%3A%22rdfs%3Alabel%22%2C%22owl%22%3A%22http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22AnnotationProperty%22%3A%22owl%3AAnnotationProperty%22%2C%22Class%22%3A%22owl%3AClass%22%2C%22comment%22%3A%22rdfs%3Acomment%22%2C%22DatatypeProperty%22%3A%22owl%3ADatatypeProperty%22%2C%22domain%22%3A%7B%22%40id%22%3A%22rdfs%3Adomain%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22ObjectProperty%22%3A%22owl%3AObjectProperty%22%2C%22range%22%3A%7B%22%40id%22%3A%22rdfs%3Arange%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22ConceptScheme%22%3A%22skos%3AConceptScheme%22%2C%22subClassOf%22%3A%7B%22%40id%22%3A%22rdfs%3AsubClassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22subPropertyOf%22%3A%7B%22%40id%22%3A%22rdfs%3AsubPropertyOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22Thing%22%3A%22owl%3AThing%22%2C%22Nothing%22%3A%22owl%3ANothing%22%2C%22unionOf%22%3A%7B%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22owl%3AunionOf%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22%40graph%22%3A%5B%7B%22label%22%3A%22Some%20property.%22%2C%22%40id%22%3A%22ex%3Aknows%22%2C%22%40type%22%3A%22ObjectProperty%22%2C%22domain%22%3A%22ex%3AFlinstone%22%2C%22range%22%3A%22_%3A1%22%7D%2C%7B%22label%22%3A%22Rubble%20class.%22%2C%22%40id%22%3A%22ex%3ARubble%22%2C%22%40type%22%3A%22Class%22%2C%22termStatus%22%3A%22stable%22%7D%2C%7B%22label%22%3A%22Flintstone%20class.%22%2C%22%40id%22%3A%22ex%3AFlintstone%22%2C%22%40type%22%3A%22Class%22%7D%2C%7B%22%40id%22%3A%22_%3A1%22%2C%22%40type%22%3A%22Class%22%2C%22unionOf%22%3A%7B%22%40list%22%3A%5B%7B%22%40id%22%3A%22ex%3AFlintstone%22%7D%2C%7B%22%40id%22%3A%22ex%3ARubble%22%7D%5D%7D%7D%5D%7D&frame=%7B%22%40context%22%3A%7B%22%40language%22%3A%22en%22%2C%22ex%22%3A%22http%3A%2F%2Fexample.com%2F%22%2C%22termStatus%22%3A%7B%22%40id%22%3A%22ex%3AtermStatus%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22unstable%22%3A%22ex%3Aunstable%22%2C%22stable%22%3A%22ex%3Astable%22%2C%22termSupersedes%22%3A%7B%22%40id%22%3A%22ex%3AtermSupersedes%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22label%22%3A%22rdfs%3Alabel%22%2C%22owl%22%3A%22http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22AnnotationProperty%22%3A%22owl%3AAnnotationProperty%22%2C%22Class%22%3A%22owl%3AClass%22%2C%22comment%22%3A%22rdfs%3Acomment%22%2C%22DatatypeProperty%22%3A%22owl%3ADatatypeProperty%22%2C%22definition%22%3A%7B%22%40id%22%3A%22skos%3Adefinition%22%2C%22%40language%22%3A%22en%22%7D%2C%22domain%22%3A%7B%22%40id%22%3A%22rdfs%3Adomain%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22ObjectProperty%22%3A%22owl%3AObjectProperty%22%2C%22range%22%3A%7B%22%40id%22%3A%22rdfs%3Arange%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22ConceptScheme%22%3A%22skos%3AConceptScheme%22%2C%22schemeOf%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40reverse%22%3A%22skos%3AinScheme%22%7D%2C%22subClassOf%22%3A%7B%22%40id%22%3A%22rdfs%3AsubClassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22subPropertyOf%22%3A%7B%22%40id%22%3A%22rdfs%3AsubPropertyOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22Thing%22%3A%22owl%3AThing%22%2C%22Nothing%22%3A%22owl%3ANothing%22%2C%22unionOf%22%3A%7B%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22owl%3AunionOf%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22%40graph%22%3A%5B%7B%22%40explicit%22%3Atrue%2C%22%40embed%22%3A%22%40last%22%2C%22%40type%22%3A%5B%22Class%22%2C%22ObjectProperty%22%2C%22DatatypeProperty%22%2C%22AnnotationProperty%22%2C%22ConceptScheme%22%5D%2C%22description%22%3A%7B%7D%2C%22definition%22%3A%7B%7D%2C%22schemeOf%22%3A%7B%22%40explicit%22%3Atrue%2C%22value%22%3A%7B%7D%2C%22definition%22%3A%7B%7D%7D%2C%22termStatus%22%3A%7B%22%40embed%22%3A%22%40never%22%2C%22%40default%22%3A%22unstable%22%7D%2C%22subClassOf%22%3A%7B%22%40default%22%3A%22Thing%22%2C%22%40explicit%22%3Atrue%2C%22%40embed%22%3A%22%40always%22%2C%22unionOf%22%3A%7B%22%40embed%22%3A%22%40never%22%7D%7D%2C%22termSupersedes%22%3A%7B%22%40embed%22%3A%22%40never%22%7D%2C%22domain%22%3A%7B%22%40default%22%3A%22Thing%22%2C%22%40explicit%22%3Atrue%2C%22%40embed%22%3A%22%40always%22%2C%22unionOf%22%3A%7B%22%40embed%22%3A%22%40never%22%7D%7D%2C%22range%22%3A%7B%22%40default%22%3A%22Thing%22%2C%22%40explicit%22%3Atrue%2C%22%40embed%22%3A%22%40always%22%2C%22unionOf%22%3A%7B%22%40embed%22%3A%22%40never%22%7D%7D%2C%22subPropertyOf%22%3A%7B%22%40embed%22%3A%22%40never%22%7D%7D%5D%7D) isolates the behavior. 

In expanded form, it looks like this (minus the context):

```json
{
  "@context": {...},
  "@graph": [
      {
          "label": "Some property.",
          "@id": "ex:knows",
          "@type": "ObjectProperty",
          "domain": "ex:Flinstone", 
          "range": "_:1"
      },
      {
          "label": "Rubble class.",
          "@id": "ex:Rubble",
	  "@type": "Class",
	  "termStatus": "stable"
      },
      {
          "label": "Flintstone class.",
          "@id": "ex:Flintstone",
	  "@type": "Class"
      },
      {
          "@id": "_:1",
          "@type": "Class",
          "unionOf": {
              "@list": [
                  {
                      "@id": "ex:Flintstone"
                  },
                  {
                      "@id": "ex:Rubble"
                  }
              ]
          }
      }			
  ]
}
```

By way of context, the exercise is rendering OWL ontologies in a framed form to be used to build documentation. The case to examine here is that the `domain` and `range` of a property can be either a single `Class` or a union of classes. The latter manifests as a blank node with a `unionOf` property with an ordered list of class ids. In English terms, here i am saying that Flintstones can know either other Flintstones, or Rubbles. 

In order to deal with this scenario, my frame `domain` and `range` are identical, and look like this:

```json
			"range": {
				"@default": "Thing",
				"@explicit": true,
				"@embed": "@always",
				"unionOf": {
					"@embed": "@never"
				}
			},
```

with the intent being that if the property (1) references just a single class, it will look like:

```json
"range": "ex:Flintstone",
```

if it (2) references a union of classes it will look like:

```json
"range": {"unionOf": ["ex:Flintstone", "ex:Rubble"]},
```

and (3) if the property is absent it will have a range of all possible classes:

```json
"range": "Thing",
```

What i am seeing in the link above is that case (2) and (3) work fine, but case (1) fails and renders the default (3). 

Is this expected behavior? 

By way of comparison, if i set:

```json
			"range": {
				"@default": "Thing",
				"@explicit": false,
				"@embed": "@always"
			},
```

but that gives me a lot of unwanted information (as in other properties on the class i had wanted to omit), and i then cannot control the output of the `unionOf` statement (see [here]()):

```json
      "domain": "ex:Flinstone",
      "range": {
        "@id": "_:b0",
        "@type": "Class",
        "unionOf": [
          {
            "@id": "ex:Flintstone",
            "@type": "Class",
            "label": "Flintstone class."
          },
          {
            "@id": "ex:Rubble",
            "@type": "Class",
            "termStatus": "stable",
            "label": "Rubble class."
          }
        ]
      },
```

There does appear to be a bug if the JSON-LD `@type` is `@vocab` and the property is absent, the defaulting mechanism renders incorrectly, compare `ex:termStatus` with `ex:supersedes` in the referenced example - it renders `ex:termStatus` rather than the alias `termStatus`. I suspect framing is compacting the output prior to defaulting.

Regards,
Patrick Johnston

**Comment by pjohnston-wiley** [comment]
Thanks, that makes sense. 

My mistake was assuming the playground would just use the defaults [from the spec](https://json-ld.org/spec/latest/json-ld-framing/#require-all-flag): "...if the value of the require all flag is false (the default)...".  I checked pyld, and that also defaults to `true`, which explains why the results were consistent; perhaps this was the original implementation default? It would be good if the reference implementations and the documentation could converge here: i think the documentation has it correctly. 

I am actually not quite sure i understand the benefit of having global options specified externally to the frame definition: it would be clearer if these were just set as processing instructions on the root frame, e.g.:

```
{
  "@context": ...,
  "@requireAll": false,
  ...
}
```

or if you don't want to pollute the basic JSON-LD vocabulary with stuff that will evolve over time:

```
{
  "@context": ...,
  "@options": {
     "requireAll": false
  },
  ...
}
```

I'd go even further and say that one should be able to specify `requireAll` on any node in the frame, much like the other framing instructions, though i guess the reason this was not done was to keep the frame spec simple? It just seems that if we are already recursing through the things like `@embed`, it would be much the same to do so for `requireAll`, especially given how crucial it is to getting my example working....

I will say that the current documentation on framing is a vast improvement over what was there around 1.0 (and i get that it was more the start of an idea back then), so thank you to the folks who have spent the time to elaborate on it. Back then, i couldn't make head or tail of it and ended up writing what was essentially my own framing algorithm. This is actually what i am now experimenting with to see whether it can be refactored to use framing. Where i have been struggling so far:

1. How the switches interact with each other to achieve a desired result is not clear, in particular whether or not the switches can be applied to any node or just the root was not obvious. Some of this is just a learning experience, but a more comprehensive framing example on the playground than the library would perhaps help. It may be because the examples in the documentation all focus on pretty much the same use case (the `contains` predicate), which is good for continuity, but not so good for learning. 
2.  Blank nodes are the bane of my existence, much as they are for anyone working with RDF. I have played with `pruneBlankNodeIdentifiers`, which isn't all that useful - since it focuses on single-use blank nodes. What i suspect a lot of folks will want is an option that eliminates the need for _any_ blank node identifiers - in other words, selective embedding, or something like `pruneBlankNodes`. If i start with a compacted graph, the framing algorithm would look whether all references to a blank node have been embedded as a result of framing, and if so eliminate the blank node left on the root.  As it is, i am finding i am having to write some post-processing to achieve this kind of result. I am happy to work on specifying this more precisely if this is something you guys would entertain.
3. The approach to framing assumes a very homogeneous graph, where all peer subjects are alike. It would be nice if, rather than invoking my least favorite and far-too-ubiquitous error message "a JSON-LD frame must be a single object", you could specify an array of things to match, which also makes for a more powerful filtering mechanism. Using the ontology example:

```json
{
  "graph": [
    {"@type": "owl:ObjectProperty", ...},
    {"@type": "owl:Class", ...}
  ]
}
```
4. In the implementations, if a property specified by the frame doesn't exist on a subject, and no default is set, the output still populates the property (albeit without applying compaction - see my original comments) and sets it to `null`. I am not sure i understand why these are output at all - setting the property to null is now saying it is defined where the source said no such thing. Especially given how iffily null json properties get interpreted by object deserializers, i would tend towards saying nothing rather than something that could be misinterpreted. At the very least turning this off should be an option.  The documentation mentions something called `@null` but then doesn't explain what it is - maybe that could be used to control when you want it output: 

```json
# Frame
{
  "@context": {... "knows": "ex:knows", "loves": "ex:loves"},
   "knows": {},
   "loves": { "@default": "@null"}
}

# Document
{
  "@type": "Flintstone"
}

# Current output (ignoring blank nodes):
{
  "@type": "Flintstone",
  "ex:knows": null,
  "ex:loves": null
}

# Ideally it would be:
{
  "@type": "Flintstone",
  "loves": null
}
```
5. It would be really nice if there were some kind of negative frame, in other words exclude results that have a specific property and/or value. This would be much less necessary with (3) and (4) in place.

### Typo in the docs

In the main documentation, just above the [introduction](https://json-ld.org/spec/latest/json-ld/#introduction), the set of documents link to JSON-LD Framing points to the JSON-LD API rather than [framing](https://json-ld.org/spec/latest/json-ld-framing/).

### A nod to RDFLib would be nice

I understand that the implementers started from first principles when building the internal graph representation for jsonld.js, but the python port is not directly compatible with [rdflib](https://github.com/RDFLib), which limits its usefulness when exploring this alongside prior W3C semantic web standards. In my case, i am doing a lot of RDF-level manipulation prior to serializing, meaning that framing is only a part of the puzzle. It wasn't the end of the world, as a nice fellow called [Simeon Warner](https://github.com/zimeon) was kind of enough to put together a basic mapping [rdlib_pyld_compat](https://github.com/zimeon/rdflib-pyld-compat/blob/master/rdflib_pyld_compat/convert.py), which i have been able to adapt for my purposes. However, it would be good to include this or something like it into pyld, and i would be happy to help if so. Even for the javascript version, being able to tap into something, say, [tinkerpop](http://tinkerpop.apache.org/)-compatible, would be nice, though perhaps outside the scope of this group. 

chz
p

**Comment by gkellogg** [comment]
Thanks for the feedback, much of this will likely wait for the WG to start up for any substantiative work. I will get the reference updated, however.

Personally, I fully agree that pyld should more natively support rdflib, but that's really an issue to take up in https://github.com/digitalbazaar/pyld.

**Comment by pjohnston-wiley** [comment]
Understood. I may get to a pull request on pyld once i've had things working for a while. I have more feedback for framing specifically, but happy to hold off until the WG kicks off.
