### ISSUE TITLE
Inclusion of @version:1.1 in documentation examples is inconsistent

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#652]
Some examples do not have `"@context": 1.1` that still require (I think) 1.1 processing.

Example 74 (Indexing languaged-tagged strings in JSON-LD with @set representation) for example uses the 1.1 feature of @container: [@language, @set] but the context does not have the @version flag.

**Comment by davidlehn** [comment]
Should the validator code (from https://github.com/json-ld/json-ld.org/pull/578) be catching such things?  travis-ci shows repo passing.

**Comment by gkellogg** [comment]
Validate code is more of a framework, it just parses JSON right now. Intention is to do complete validation,  it need to tie various pieces together. @iherman also has some other ideas for displaying examples that might help.

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/39.
