### ISSUE TITLE
infinite recursion in @reverse properties

### ISSUE THREAD

**Issue by eroux** [json-ld/json-ld.org#653]
It would be nice to have the same possiblity of infinite recursion in the `@reverse` properties as there are in non-reverse ones ([example](https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22prefLabel%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxHasSubClass%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%7D%5D%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxHasSubClass%22%3A%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%7D%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%2C%22%40type%22%3A%22Taxonomy%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%2C%22%40type%22%3A%22Taxonomy%22%7D%5D%7D&frame=%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40context%22%3A%7B%22children%22%3A%7B%22%40reverse%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%7D%2C%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D&context=%7B%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22prefLabel%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D)), currently recursion only works as many times as the frame defines it ([example](https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40type%22%3A%22Taxonomy%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605%22%7D%5D%2C%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D&frame=%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40context%22%3A%7B%22children%22%3A%7B%22%40reverse%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%7D%2C%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%2C%22children%22%3A%7B%7D%7D)).

Copy/pasting the examples (and removing `@context`s):

in the working case, I have

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "@type": "Taxonomy",
      "taxHasSubClass": [
        {
          "@id": "bdr:O9TAXTBRC201605_0001"
        },
        {
          "@id": "bdr:O9TAXTBRC201605_0010"
        }
      ]
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0001",
      "@type": "Taxonomy",
      "taxHasSubClass": {
        "@id": "bdr:O9TAXTBRC201605_0002"
      }
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0002",
      "@type": "Taxonomy"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0010",
      "@type": "Taxonomy"
    }
  ]
}
```

and frame

```json
{ 
  "@id" : "bdr:O9TAXTBRC201605",
  "@context" : {
    "children": { "@reverse": "http://purl.bdrc.io/ontology/core/taxSubclassOf" }, 
    "taxSubclassOf" : {
      "@id" : "http://purl.bdrc.io/ontology/core/taxSubclassOf",
      "@type" : "@id"
    },
    "@vocab" : "http://purl.bdrc.io/ontology/core/",
    "bdr" : "http://purl.bdrc.io/resource/"
  }
}
```

that produces the nice

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "@type": "Taxonomy",
      "taxHasSubClass": [
        {
          "@id": "bdr:O9TAXTBRC201605_0001",
          "@type": "Taxonomy",
          "taxHasSubClass": {
            "@id": "bdr:O9TAXTBRC201605_0002",
            "@type": "Taxonomy"
          }
        },
        {
          "@id": "bdr:O9TAXTBRC201605_0010",
          "@type": "Taxonomy"
        }
      ]
    }
  ]
}
```

but for the opposite:

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "@type": "Taxonomy"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0001",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0002",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605_0001"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0010",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605"
    }
  ]
}
```

and the frame

```json
{
  "@id": "bdr:O9TAXTBRC201605",
  "@context": {
    "children": {
      "@reverse": "http://purl.bdrc.io/ontology/core/taxSubclassOf"
    },
    "taxSubclassOf": {
      "@id": "http://purl.bdrc.io/ontology/core/taxSubclassOf",
      "@type": "@id"
    },
    "@vocab": "http://purl.bdrc.io/ontology/core/",
    "bdr": "http://purl.bdrc.io/resource/"
  },
  "children": {}
}
```

I'm not getting all the recursion, only

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "children": [
        {
          "@id": "bdr:O9TAXTBRC201605_0001",
          "@type": "Taxonomy",
          "taxSubclassOf": "bdr:O9TAXTBRC201605"
        },
        {
          "@id": "bdr:O9TAXTBRC201605_0010",
          "@type": "Taxonomy",
          "taxSubclassOf": "bdr:O9TAXTBRC201605"
        }
      ],
      "@type": "Taxonomy"
    }
  ]
}
```

**Comment by gkellogg** [comment]
Moved to w3c/json-ld-framing#5.
