### ISSUE TITLE
Use proper Wikidata URIs

### ISSUE THREAD

**Issue by Tpt** [json-ld/json-ld.org#664]
Wikidata entity URIs follow the pattern http://www.wikidata.org/entity/QXXX like http://www.wikidata.org/entity/Q42.

https://json-ld.org/spec/latest/json-ld-api-best-practices/ is using  URIs like https://www.wikidata.org/wiki/Q76 that are the URIs of the Wikidata wiki pages describing the items.

**Comment by todrobbins** [comment]
Note though that Wikidata URIs are all `https` not `http`

**Comment by elf-pavlik** [comment]
This page suggest `http` https://www.wikidata.org/wiki/Wikidata:Data_access#Linked_Data_interface
> Each item or property has a persistent URI that you obtain by appending its ID (such as Q42 or P12) to the Wikidata concept namespace: `http://www.wikidata.org/entity/`

**Comment by Tpt** [comment]
An other example: `curl -L 'http://www.wikidata.org/entity/Q1' --header 'Accept: text/turtle'` is going to return `@prefix wd: <http://www.wikidata.org/entity/>` and uses this prefix for the item UIs.

**Comment by todrobbins** [comment]
Interesting. Why the inconsistency then?
