### ISSUE TITLE
how can we describe a available operations for a specific api in json-ld? 

### ISSUE THREAD

**Issue by videni** [json-ld/json-ld.org#666]
for example,  when user try to  view a resource , the client  might show an edit button when user has edit permission.`HAL` has links, how can we do this in jsonld?

**Comment by elf-pavlik** [comment]
You might find http://www.hydra-cg.com/ interesting, it uses JSON-LD to express hypermedia controls in web APIs. One of the JSON-LD 1.0 editors started and still leads this effort.

**Comment by videni** [comment]
@elf-pavlik  , I am using ApiPlatform, it supports json-ld and HAL together , I don't find any documents in hydra-cg  that describe `_links` equivalent in HAL.

@BigBlueHat,  good idea, thanks for sharing.

**Comment by elf-pavlik** [comment]
This section shows usage of `hydra:Link` http://www.hydra-cg.com/spec/latest/core/#adding-affordances-to-representations

Possibly this comparison of formats can also come useful: https://dracoblue.net/dev/overview-of-json-hypermedia-link-formats/

> for example, when user try to view a resource , the client might show an edit button when user has edit permission.HAL has links, how can we do this in jsonld?

You can find example of expressing *edit* operation in Hydra here: https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases/6.updating-event.md

In that case it describes making HTTP PUT request to the same resource, so it actually doesn't link to any other resource and would not use `hydra:Link`
