### ISSUE TITLE
Inconsistencies in Create Term Definition algorithm of json-ld-api spec

### ISSUE THREAD

**Issue by lutzhelm** [json-ld/json-ld.org#672]
In the following line of step 19, `defined` should probably be replaced with `definition`:
https://github.com/json-ld/json-ld.org/blob/77d85b19c4d368580eb7b266d41e953ea199ec17/spec/latest/json-ld-api/index.html#L1219

The listing of allowed keywords in step 21 is missing the `@language` keyword (otherwise step 18 would be pointless):
https://github.com/json-ld/json-ld.org/blob/77d85b19c4d368580eb7b266d41e953ea199ec17/spec/latest/json-ld-api/index.html#L1238-L1243

**Comment by gkellogg** [comment]
Thanks, these should go on w3c/json-ld-api, as this is the active repo now.
