### ISSUE TITLE
Problem with 1.0.2 version during webpack compilation rdf-canonize error arose.

### ISSUE THREAD

**Issue by ArekMiszcz** [json-ld/json-ld.org#683]
There is a problem with json-ld rdf-canonize dependence. This package contain es6 syntax which fails my application.

**Comment by davidlehn** [comment]
Please move this to https://github.com/digitalbazaar/jsonld.js/issues.  Quick answer is both jsonld.js and rdf-canonize are using ES6+ syntax.  You'll need to setup webpack to use the pre-built dist/ files or use babel or similar to transpile the code for your target environment.  I'm not sure if there are babel hints we could add to make this more automatic.

**Comment by ArekMiszcz** [comment]
Ok, Thanks a lot for this answer.
