### ISSUE TITLE
Updated playground breaks spec examples

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#693]
Changing the default playground to 1.1 is fine, but removing /playground-dev brakes the specs, which use this in the "Open in playground" link. We should redirect this to /playground (without loosing the query args). The specs can be updated, but not the already-published working drafts.

**Comment by davidlehn** [comment]
I did add a redirect for that purpose.  I think it was just a typo that I somehow missed while testing.  Does this fix work?
https://github.com/json-ld/json-ld.org/commit/ec3882958a9d87a273dd0b959d55c284aa1647a8

**Comment by gkellogg** [comment]
Not loading for me; try one of the examples from the spec.

**Comment by BigBlueHat** [comment]
Good to know this is going on. I came to file a redirect bug issue. 😄 Partly because the message is still above the playground which states there's a dev playground I can use...which sends me back to where I was... 😕 Might want to at least remove the message.

**Comment by BigBlueHat** [comment]
Also, not sure this is actually working...the `@nest` example from the spec (at least) isn't currently working: [example 71](https://json-ld.org/playground-dev/#startTab=tab-expand&json-ld=%7B%0A%20%20%22%40context%22%3A%20%7B%0A%20%20%20%20%22%40version%22%3A%201.1%2C%0A%20%20%20%20%22skos%22%3A%20%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%0A%20%20%20%20%22labels%22%3A%20%22%40nest%22%2C%0A%20%20%20%20%22main_label%22%3A%20%7B%22%40id%22%3A%20%22skos%3AprefLabel%22%2C%20%22%40nest%22%3A%20%22labels%22%7D%2C%0A%20%20%20%20%22other_label%22%3A%20%7B%22%40id%22%3A%20%22skos%3AaltLabel%22%2C%20%22%40nest%22%3A%20%22labels%22%7D%2C%0A%20%20%20%20%22homepage%22%3A%20%7B%22%40id%22%3A%20%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fhomepage%22%2C%20%22%40type%22%3A%20%22%40id%22%7D%0A%20%20%7D%2C%0A%20%20%22%40id%22%3A%20%22http%3A%2F%2Fexample.org%2Fmyresource%22%2C%0A%20%20%22homepage%22%3A%20%22http%3A%2F%2Fexample.org%22%2C%0A%20%20%22labels%22%3A%20%7B%0A%20%20%20%20%20%22main_label%22%3A%20%22This%20is%20the%20main%20label%20for%20my%20resource%22%2C%0A%20%20%20%20%20%22other_label%22%3A%20%22This%20is%20the%20other%20label%22%0A%20%20%7D%0A%7D)

**Comment by davidlehn** [comment]
Is there some strange caching going on here?  Check network traffic and see if new pages are actually fetched.  Or just try a force reload.  Everything loads for me.  There are no links to the former playground-dev page on the site.  Links to former dev page should redirect to main page and still work.

@BigBlueHat Are you saying the `@nest` example output is wrong or it just doesn't load at all?

**Comment by BigBlueHat** [comment]
Yep. It's caching. A "shift + refresh" did the trick...but folks won't know to do that. 😢 

Thoughts? 💭

**Comment by gkellogg** [comment]
One way to avoid this is to use some randomized string as a query to the URLs for the various resources. Asset packages I use with Ruby handle this automatically.

**Comment by BigBlueHat** [comment]
In this case it's not the sub-resources/dependencies being aggressively cashed, but the page itself--hence the visibility of the notice about their being a dev playground. That URL can't be updated ('cause it's linked all the places), so this is probably something unfixable and we can only wait for `Expires` headers (or whatever caused this) to expire.

But someone with server config access would have to inform what's actually causing the caching issue...which could even be a fronting proxy of some kind...

Yeah Webz! 🕸

**Comment by davidlehn** [comment]
It's just apache.  Looks like it just sends etag and last modified date.  Those usually work ok.  I don't have the issue so it's hard to debug it.

**Comment by gkellogg** [comment]
Fixed now.
