### ISSUE TITLE
Update playground content negotiation for schema.org.

### ISSUE THREAD

**Issue by davidlehn** [json-ld/json-ld.org#729]
The playground, jsonld.js, and/or the document loader it uses needs to be updated to handle how sites such as schema.org handle content negotiation for contexts.

See:
https://github.com/schemaorg/schemaorg/issues/2578

**Comment by gkellogg** [comment]
See https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-632808985. This might not be an issue, after all.

**Comment by davidlehn** [comment]
schema.org using Link headers now.  jsonld.js XHR code had a bug.  Fixed via https://github.com/digitalbazaar/jsonld.js/pull/397.
