### ISSUE TITLE
Nested context compaction w/ multiple types

### ISSUE THREAD

**Issue by sharpfives** [json-ld/json-ld.org#763]
I've noticed some interesting behavior when compacting JSON-LD input of a node that contains multiple types, using a context that contains nested contexts specific to those types. The following example contains a node with two types, `["http://typeA", "http://typeB"]`, and a single name property `"http://name"` which should compact to either `"nameA"` or `"nameB"` depending on the type. In this case the node has both types, so which compacted name property should be used?

[Example case](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fobject%22%2C%22%40type%22%3A%5B%22http%3A%2F%2FtypeA%22%2C%22http%3A%2F%2FtypeB%22%5D%2C%22http%3A%2F%2Fname%22%3A%22Bob%22%7D%5D&context=%7B%22%40context%22%3A%7B%22TypeA%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeA%22%2C%22%40context%22%3A%7B%22nameA%22%3A%22http%3A%2F%2Fname%22%7D%7D%2C%22TypeB%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeB%22%2C%22%40context%22%3A%7B%22nameB%22%3A%22http%3A%2F%2Fname%22%7D%7D%7D%7D)

The current result is that `"http://name"` is compacted to `"nameA"`. 

After some experimentation, the order of operation in which the nested contexts are applied seems to be relative to the length and alphabetical sorting of the compacted property name. So, changing `"nameA"` in TypeA's context to `"nameABC"` results in `"http://name"` being compacted to `"nameB"` using TypeB's context ([example](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fobject%22%2C%22%40type%22%3A%5B%22http%3A%2F%2FtypeA%22%2C%22http%3A%2F%2FtypeB%22%5D%2C%22http%3A%2F%2Fname%22%3A%22Bob%22%7D%5D&context=%7B%22%40context%22%3A%7B%22TypeA%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeA%22%2C%22%40context%22%3A%7B%22nameABC%22%3A%22http%3A%2F%2Fname%22%7D%7D%2C%22TypeB%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeB%22%2C%22%40context%22%3A%7B%22nameB%22%3A%22http%3A%2F%2Fname%22%7D%7D%7D%7D)), but, changing `"nameA"` to `"name0"` still results in TypeA's `"name0"` in the output ([example](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fobject%22%2C%22%40type%22%3A%5B%22http%3A%2F%2FtypeA%22%2C%22http%3A%2F%2FtypeB%22%5D%2C%22http%3A%2F%2Fname%22%3A%22Bob%22%7D%5D&context=%7B%22%40context%22%3A%7B%22TypeA%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeA%22%2C%22%40context%22%3A%7B%22name0%22%3A%22http%3A%2F%2Fname%22%7D%7D%2C%22TypeB%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeB%22%2C%22%40context%22%3A%7B%22nameB%22%3A%22http%3A%2F%2Fname%22%7D%7D%7D%7D)). In summary, it chose the shortest compacted property name first, followed by the first alphabetically sorted property name.

I would like to propose a more dynamic approach to applying a nested context to nodes with multiple types, rather than the current sorting approach. Some options / thoughts for discussion:

1. Since `@type` is an array, would using the order the types on a node be appropriate for determining the order in which contexts are applied? Currently, reversing the order of the types in the input to `["http://typeB", "http://typeA"]` yields the same behavior above, but perhaps this could imply the order of context preference.
2. Would there be any harm in the compacted result containing BOTH a `"nameA"` and `"nameB"` property, since they refer to the same value and IRI? I've noted that the reverse expansion of this case contains two `@value`s rather than one, as a negative side effect in its current state. [Expanded result](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22TypeA%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeA%22%2C%22%40context%22%3A%7B%22nameA%22%3A%22http%3A%2F%2Fname%22%7D%7D%2C%22TypeB%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeB%22%2C%22%40context%22%3A%7B%22nameB%22%3A%22http%3A%2F%2Fname%22%7D%7D%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fobject%22%2C%22%40type%22%3A%5B%22TypeA%22%2C%22TypeB%22%5D%2C%22nameA%22%3A%22Bob%22%2C%22nameB%22%3A%22Bob%22%7D%5D%7D&context=%7B%22%40context%22%3A%7B%22TypeA%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeA%22%2C%22%40context%22%3A%7B%22nameA%22%3A%22http%3A%2F%2Fname%22%7D%7D%2C%22TypeB%22%3A%7B%22%40id%22%3A%22http%3A%2F%2FtypeB%22%2C%22%40context%22%3A%7B%22nameB%22%3A%22http%3A%2F%2Fname%22%7D%7D%7D%7D)
3. Perhaps the context itself could dictate the order of preference in which its sub-contexts are applied.

Thank you for your time and consideration!

-Alex

**Comment by gkellogg** [comment]
Determining the proper term to use when compacting is covered by the [Term Selection](https://www.w3.org/TR/json-ld11-api/#term-selection) algorithm in the API using the active context. Given two type-scoped context, the order in which they are applied to the active context is also determined algorithmically in step 11 of the [Compaction Algorithm](https://www.w3.org/TR/json-ld11-api/#compaction-algorithm), which does involve ordering those expanded types lexicographically. It's important that these are handled in the specified order for interoperability.

The general term selection algorithm was determined in the JSON-LD 1.0 timeframe by closing the shortest and lexicographically earliest term meeting the criterion; only in JSON-LD 1.1 were type-scoped contexts introduced, with their own ordering considerations.

While a future WG could consider revising this, it would be a tall order to do so and introduce incompatibilities.
