### ISSUE TITLE
jsonld playground does not work with remote contexts anymore 

### ISSUE THREAD

**Issue by bertvannuffelen** [json-ld/json-ld.org#764]
Example https://w3c.github.io/json-ld-syntax/#example-sourcing-a-context-in-a-type-scoped-context-and-setting-it-to-propagate

does not work anymore. An internal error is reported: Could not load content for webpack://[name]/jsonld.min.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME).

kr,

Bert

**Comment by gkellogg** [comment]
It seems to work for me now, at least [link](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22MyType%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.com%2Fvocab%23MyType%22%2C%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40import%22%3A%22https%3A%2F%2Fjson-ld.org%2Fcontexts%2Fremote-context.jsonld%22%2C%22%40propagate%22%3Atrue%7D%7D%7D%7D&context=https%3A%2F%2Fjson-ld.org%2Fcontexts%2Fremote-context.jsonld). Perhaps an intermittent error?
