### ISSUE TITLE
specify JsonLdOptions in playground

### ISSUE THREAD

**Issue by James2516** [json-ld/json-ld.org#767]
How do I specify JsonLdOptions on https://json-ld.org/playground/?
Eg. I want to set [compactArrays](https://www.w3.org/TR/json-ld11-api/#dom-jsonldoptions-compactarrays) to true.

**Comment by davidlehn** [comment]
I just added the feature.  Click on the checkbox in the "Options" tab.

Note that `compactArrays` already defaults to `true`.  Did you mean you wanted to set it to `false`?  Or was it maybe some other issue?

**Comment by gkellogg** [comment]
A couple of other options the Distiller has are `extractAllScripts` (probably not appropriate for the playground), `useNativeTypes`, `lowercaseLanguage`, `rdfDirection`, `omitDefault`, `requireAll`, and `explicit`.

**Comment by davidlehn** [comment]
> A couple of other options the Distiller has are `extractAllScripts` (probably not appropriate for the playground), `useNativeTypes`, `lowercaseLanguage`, `rdfDirection`, `omitDefault`, `requireAll`, and `explicit`.

PRs welcome. ;-)

A whole new version is needed, just trying to hack in easy features here.

@gkellogg As I was adding that feature I couldn't figure out how the Distiller `compactArrays` checkbox worked.  It's not checked by default, but I assume true by default?  And checked or not, the result of compaction seems to look the same.  Maybe I missed something.

**Comment by gkellogg** [comment]
It probably doesn't work very well. I don't quite remember how defaults are used in the UI. In the CLI, which it is based on, it would be --no-compactArrays, but how it was translated I don't recall.
