### ISSUE TITLE
Consider value as part of vocabulary-IRI

### ISSUE THREAD

**Issue by weissjoh** [json-ld/json-ld.org#771]
I have the case that within a JSON document is included which contains an attribute with a string. This value is pointing to an item of an enumeration resp. a named individual. However, just the name and not the full IRI.

```json
{
  "@context": {
    "enumtype": {
      "@context": { "@base": "http://myvocab.com/devices#" },
      "@type": "@id",
      "@id": "http://myvocab.com/ownership#belongsTo"
    }
  },
  "@id": "http://example.com/id-1",
  "enumtype": "notebook"
}
```

I do get back the following turtle:

```text
<http://example.com/id-1> <http://myvocab.com/ownership#belongsTo> <http://myvocab.com/notebook> .
```

However, I am expecting the following result as turtle:

```text
<http://example.com/id-1> <http://myvocab.com/ownership#belongsTo> <http://myvocab.com/devices#notebook> .
```

Interestingly the ``devices#`` from the ``@base`` definition is cut off. I am wondering if there is some tweak possible to get my expected result. [Here is the link to JSON-LD Playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%7B%22enumtype%22%3A%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fmyvocab.com%2Fdevices%23%22%7D%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22http%3A%2F%2Fmyvocab.com%2Fownership%23belongsTo%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2Fid-1%22%2C%22enumtype%22%3A%22notebook%22%7D).

**Comment by niklasl** [comment]
Since `enumtype` is defined with `@type: @id`, its value is treated as a relative IRI, which is then resolved against the `@base` in the term-scoped context. To get what you want here, you need to express it like this:
```json
{
  "@context": {
    "enumtype": {
      "@context": {
        "@vocab": "http://myvocab.com/devices#"
      },
      "@type": "@vocab",
      "@id": "http://myvocab.com/ownership#belongsTo"
    }
  },
  "@id": "http://example.com/id-1",
  "enumtype": "notebook"
}
```

**Comment by weissjoh** [comment]
@niklasl amazing. Thank you very much for your help. This actually solves the problem 👍
