### ISSUE TITLE
compactIri doesn't work when  there are 2 different uris with the same shortname 

### ISSUE THREAD

**Issue by garpinc** [json-ld/json-ld.org#772]
String compactIri(String iri, Object value, boolean relativeToVocab, boolean reverse) {

calls:
        if (relativeToVocab && getInverse().containsKey(iri)) {

I have 2 different uris which map to the same short name but it seems the inverse  function throws away the relationship of  one of the uris.

My json that it was compacting has one context at the top of the json with all contexts of the types in the file.

I can imagine that if you receive json with the same short name in 2 different types that it would have to scope the right context at the level of the type in order to  get the right expanded url but in my case I don't need to worry about this because I'm not trying to do the expansion since it's already expanded directly from rdf. I already have the uris and I just want the right short name but the way the code is written doesn't seem to allow that.

Please advise

**Comment by pchampin** [comment]
@garpin could you please provide a minimal example showing your problem, as;
- the input in expanded form
- the context
- the expected output in compact form
- the obtained output

Did you test it with different implementations? This would help determining whether this is an issue with the spec, or an implementation bug.
