### ISSUE TITLE
json-ld.org site is down 

### ISSUE THREAD

**Issue by filip26** [json-ld/json-ld.org#802]
Hi,
it seems the site is down for the last couple of days. Getting an error:

```
https://json-ld.org/ is unreachable.
ERR_ADDRESS_UNREACHABLE
```

Thank you for maintaining the site! I use the playground regularly.

**Comment by davidlehn** [comment]
Yup, it's down, sorry about that.  Will get it fixed soon.

**Comment by davidlehn** [comment]
Site is back up.  There were some hosting issues and we didn't have time to immediately address them.
