### ISSUE TITLE
JSON-LD for R?

### ISSUE THREAD

**Issue by ran-codes** [json-ld/json-ld.org#807]
Is there tooling for programming in R?

I don't see it on the home page

**Comment by davidlehn** [comment]
I know nothing of R.  Google says there is a jsonld.js wrapper.  Looks out-of-date, but maybe a place to start.
https://www.google.com/search?q=json-ld+r
https://cran.r-project.org/web/packages/jsonld/index.html
https://github.com/ropensci/jsonld

**Comment by ran-codes** [comment]
thanks for the suggestions!
