### ISSUE TITLE
JSON-LD Context similarity to XML External Entity attack

### ISSUE THREAD

**Issue by hmottestad** [json-ld/json-ld.org#825]
> An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

JSON-LD supports referencing a context stored online or on the local file system. This seems to allow for the same attack surface as with XML External Entity. 

See: https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing

**Comment by BigBlueHat** [comment]
Closing in favor of keeping conversation on https://github.com/w3c/json-ld-syntax/issues/421

Thanks for your participation, @hmottestad!
