### ISSUE TITLE
The site is dead?

### ISSUE THREAD

**Issue by softmarshmallow** [json-ld/json-ld.org#841]
<img width="1154" alt="Screenshot 2024-05-22 at 1 30 05 AM" src="https://github.com/json-ld/json-ld.org/assets/16307013/46485710-2a33-43c4-a83b-411e9421e2ee">

**Comment by davidlehn** [comment]
Works for me.

**Comment by gkellogg** [comment]
[Seems to be running](https://downforeveryoneorjustme.com/json-ld.org?proto=https).

**Comment by TallTed** [comment]
The site is alive.
