### ISSUE TITLE
JSON-LD 1.1 not supported in playground?

### ISSUE THREAD

**Issue by cmahnke** [json-ld/json-ld.org#846]
This is certainly just a wrong error message?

<img width="639" alt="Bildschirmfoto 2024-10-17 um 12 26 47" src="https://github.com/user-attachments/assets/1ed02b57-6f7f-42b3-9807-3664ac2c3240">

**Comment by davidlehn** [comment]
The error message there could be improved.  I made an issue for that: https://github.com/digitalbazaar/jsonld.js/issues/559.

**Comment by cmahnke** [comment]
@davidlehn Thanks, your right. I'm not sure what I should think of this choice of the datatype, but am not up to complain...
